### ISSUE TITLE
Optimize transpose operation using shared memory for LLVMGPU backend

### ISSUE THREAD

**Issue by ThomasRaoux** [openxla/iree#10005]
### Request description

Currently transpose operations are being vectorized (as long as they are aligned) and we usually end up with code that looks like:
```
r0 = load
r1 = load
r2 = load
r3 = load
store4 { r0, r1, r2, r3 }
```

We could optimize it using shared memory to be able to do load4 from main memory.

We should do:
```
{r0, r1, r2, r3} = load4
store4 {r0, r1, r2, r3} -> shared memory
m0 = load_shared_memory
m1 = load_shared_memory
m2 = load_shared_memory
m3 = load_shared_memory 
store4 {m0, m1, m2, m3} -> global
```

Note that In order to avoid bank conflicts we should make sure the shared memory allocation is aligned on 32 + 1.
 
We should start with aligned case and then this can be combined with https://github.com/iree-org/iree/issues/10003 to handle unaligned cases.

### What component(s) does this issue relate to?

Compiler

**Comment by alliemartens** [comment]
@okkwon Any idea of priority for this?

**Comment by okkwon** [comment]
It is already set to P2.

**Comment by ThomasRaoux** [comment]
Here is a summary of what we want to do:
https://developer.nvidia.com/blog/efficient-matrix-transpose-cuda-cc/

**Comment by ThomasRaoux** [comment]
Done and working
