### ISSUE TITLE
Output the compile args from iree_bytecode_module

### ISSUE THREAD

**Issue by pzread** [openxla/iree#10155]
The CMake rule `iree_bytecode_module` not only takes the compile args from the caller but also adds some flags by itself to build the modules.

It will help people debug the issues of modules if `iree_bytecode_module` can dump the complete compile flags.

**Comment by ScottTodd** [comment]
Full compile commands are available in the `build.ninja` file in the build directory when using Ninja and other generators may have other ways to get that info. I don't think we should add any of our own logic on top of that.
