### ISSUE TITLE
Long compilation time of quantized MobileBert on RISC-V

### ISSUE THREAD

**Issue by pzread** [openxla/iree#10236]
Right now the compiler takes ~3mins to compile `MobileBert [int8]` for RV64, which looks abnormal
https://perf.iree.dev/serie?IREE?MobileBertSquad%20%5Bint8%5D%20(TFLite)%20CPU-RV64-Generic%20full-inference%2Cdefault-flags%20%5Bcompilation%3Amodule%3Acompilation-time%5D

And on RV32 it takes ~10mins
https://perf.iree.dev/serie?IREE?MobileBertSquad%20%5Bint8%5D%20(TFLite)%20CPU-RV32-Generic%20full-inference%2Cdefault-flags%20%5Bcompilation%3Amodule%3Acompilation-time%5D

**Comment by pzread** [comment]
Realized the RV32 takes even longer, updated the issue.

**Comment by GMNGeoffrey** [comment]
Looks like this just got a sizable speedup from https://github.com/iree-org/iree/pull/10179. I was seeing twice as long as of this morning

**Comment by dcaballe** [comment]
Yes, 3 mins is what I see locally. This is mostly due to the massive unrolling that is happening. We are working on improving this issue...

**Comment by GMNGeoffrey** [comment]
You mean for RV64? RV32 looks to be 10 minutes right now

**Comment by dcaballe** [comment]
Yes, RV64. We are only using RV32 for Person Detect in practice (@hcindyl).

**Comment by GMNGeoffrey** [comment]
If you're not actively optimizing compilation time on RV32 Mobile Bert I'd like to merge https://github.com/iree-org/iree/pull/10234

**Comment by hcindyl** [comment]
MobileBert is not a primary focus for RV32 codegen. I am okay with merging #10234

**Comment by allieculp** [comment]
Looks like this is merged - can we close?
