### ISSUE TITLE
Re-enable the compile_sample_module.py test

### ISSUE THREAD

**Issue by okkwon** [openxla/iree#10265]
### What happened?

The test was disabled during the recent LLVM version up process. The test tries to import chlo but fails to find it due to the recent stablehlo transition.

The test is commented out here: compiler/src/iree/compiler/API/python/test/transforms/ireec/CMakeLists.txt

### What component(s) does this issue relate to?

Python

**Comment by stellaraccident** [comment]
Fixed and enabled at some point.
