### ISSUE TITLE
benchmark_suites/TF/vmfb/minilm-l12-h384-uncased-seqlen128 requires CUDA but builds when disabled

### ISSUE THREAD

**Issue by stellaraccident** [openxla/iree#10455]
With CUDA disabled, the `benchmark_suites/TF/vmfb/minilm-l12-h384-uncased-seqlen128` benchmark is attempting to be compiled anyway. This causes an error like:

```
iree-compile: Unknown command line argument '--iree-hal-cuda-llvm-target-arch=sm_80'.  Try: '/usr/local/google/home/laurenzo/src/iree-build/tools/iree-compile --help'
iree-compile: Did you mean '--iree-llvm-target-abi=sm_80'?
```

Can be repro'd via:

```
pip install iree-tools-tf iree-tools-tflite -f https://github.com/iree-org/iree/releases
cmake -DIREE_BUILD_BENCHMARKS=ON .
ninja iree-benchmark-suites -k 500
```

**Comment by allieculp** [comment]
Moving to backlog due to the age of the issue - please bump up in priority if needed.

**Comment by ScottTodd** [comment]
This was fixed by https://github.com/openxla/iree/pull/10508 (github tagged but didn't close)
