### ISSUE TITLE
Generalize the usage of `LoopTilingAndDistributionInfo`

### ISSUE THREAD

**Issue by okkwon** [openxla/iree#10577]
### Request description

The `LoopTilingAndDistributionInfo` structure is used in multiple places to pattern-match the tile and distribution loops. There is a plan to change the distribution loop nest by some explicit op, and this structure's usage also needs to be considered.

The effort is to fill the gap between IREE and the upstream way by generalizing the information represented by the structure. The best result would be to remove the structure completely.

### What component(s) does this issue relate to?

Compiler

**Comment by MaheshRavishankar** [comment]
This isnt needed anymore. Closing
