### ISSUE TITLE
Vectorize pooling operations

### ISSUE THREAD

**Issue by dcaballe** [openxla/iree#10670]
Pooling operations are not vectorized in DeepLabV3 and MobileNetV1. The performance impact is significantly lower than not vectorizing convolutions but I think it's important that we have it working as well.

The main problem is that pooling operations are represented as named operations on Linalg and we don't have specific vectorization patterns for them. For example, the `linalg.pooling_nhwc_sum` operation below completely skips the Vector dialect:

```
func.func @main_dispatch_69_pooling_nhwc_sum_1x1x1x160x33x33() {                                                                                                                                     
  %c160 = arith.constant 160 : index                                                                                                                                                                 
  %c2090880 = arith.constant 2090880 : index                                                                                                                                                         
  %c0 = arith.constant 0 : index                                                                                                                                                                     
  %cst = arith.constant 0.000000e+00 : f32                                                                                                                                                           
  %cst_0 = arith.constant 1.089000e+03 : f32                                                                                                                                                         
  %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) offset(%c2090880) alignment(64) : memref<1x33x33x160xf32>                                                                
  memref.assume_alignment %0, 64 : memref<1x33x33x160xf32>                                                                                                                                           
  %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) offset(%c0) alignment(64) : memref<1x1x1x160xf32>                                                                        
  memref.assume_alignment %1, 64 : memref<1x1x1x160xf32>                                                                                                                                             
  %2 = memref.alloca() {alignment = 128 : i64} : memref<33x33xf32>                                                                                                                                   
  %workgroup_id_x = hal.interface.workgroup.id[0] : index                                                                                                                                            
  %workgroup_count_x = hal.interface.workgroup.count[0] : index                                                                                                                                      
  %3 = affine.apply affine_map<()[s0] -> (s0 * 32)>()[%workgroup_id_x]                                                                                                                               
  %4 = affine.apply affine_map<()[s0] -> (s0 * 32)>()[%workgroup_count_x]                                                                                                                            
  scf.for %arg0 = %3 to %c160 step %4 {                                                                                                                                                              
    %5 = memref.subview %1[0, 0, 0, %arg0] [1, 1, 1, 32] [1, 1, 1, 1] : memref<1x1x1x160xf32> to memref<1x1x1x32xf32, strided<[160, 160, 160, 1], offset: ?>>                                        
    %6 = memref.subview %0[0, 0, 0, %arg0] [1, 33, 33, 32] [1, 1, 1, 1] : memref<1x33x33x160xf32> to memref<1x33x33x32xf32, strided<[174240, 5280, 160, 1], offset: ?>>                              
    linalg.fill ins(%cst : f32) outs(%5 : memref<1x1x1x32xf32, strided<[160, 160, 160, 1], offset: ?>>)                                                                                              
    linalg.pooling_nhwc_sum {dilations = dense<1> : vector<2xi64>, lowering_config = #iree_codegen.lowering_config<tile_sizes = [[0, 0, 0, 32, 0, 0]]>, strides = dense<33> : vector<2xi64>} ins(%6, %2 : memref<1x33x33x32xf32, strided<[174240, 5280, 160, 1], offset: ?>>, memref<33x33xf32>) outs(%5 : memref<1x1x1x32xf32, strided<[160, 160, 160, 1], offset: ?>>)                                  
    linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} outs(%5 : memref<1x1x1x32xf32, strided<[160, 160, 160, 1], offset: ?>>) {                                                                                                                                                                      
    ^bb0(%arg1: f32):                                                                                                                                                                                
      %7 = arith.divf %arg1, %cst_0 : f32                                                                                                                                                            
      linalg.yield %7 : f32                                                                                                                                                                          
    }                                                                                                                                                                                                
  }                                                                                                                                                                                                  
  return                                                                                                                                                                                             
}
```

and it's then lowered to scf:

```
  scf.for %arg0 = %2 to %c160 step %3 {
    %4 = memref.subview %1[0, 0, 0, %arg0] [1, 1, 1, 32] [1, 1, 1, 1] : memref<1x1x1x160xf32> to memref<1x1x1x32xf32, strided<[160, 160, 160, 1], offset: ?>>
    %5 = memref.subview %0[0, 0, 0, %arg0] [1, 33, 33, 32] [1, 1, 1, 1] : memref<1x33x33x160xf32> to memref<1x33x33x32xf32, strided<[174240, 5280, 160, 1], offset: ?>>
    scf.for %arg1 = %c0 to %c1 step %c1 {
      scf.for %arg2 = %c0 to %c1 step %c1 {
        scf.for %arg3 = %c0 to %c1 step %c1 {
          scf.for %arg4 = %c0 to %c32 step %c1 {
            memref.store %cst, %4[%arg1, %arg2, %arg3, %arg4] : memref<1x1x1x32xf32, strided<[160, 160, 160, 1], offset: ?>>
          }
        }
      }
    }
    scf.for %arg1 = %c0 to %c1 step %c1 {
      scf.for %arg2 = %c0 to %c1 step %c1 {
        scf.for %arg3 = %c0 to %c1 step %c1 {
          scf.for %arg4 = %c0 to %c32 step %c1 {
            scf.for %arg5 = %c0 to %c33 step %c1 {
              scf.for %arg6 = %c0 to %c33 step %c1 {
                %6 = affine.apply affine_map<(d0, d1) -> (d0 * 33 + d1)>(%arg2, %arg5)
                %7 = affine.apply affine_map<(d0, d1) -> (d0 * 33 + d1)>(%arg3, %arg6)
                %8 = memref.load %5[%arg1, %6, %7, %arg4] : memref<1x33x33x32xf32, strided<[174240, 5280, 160, 1], offset: ?>>
                %9 = memref.load %4[%arg1, %arg2, %arg3, %arg4] : memref<1x1x1x32xf32, strided<[160, 160, 160, 1], offset: ?>>
                %10 = arith.addf %9, %8 : f32
                memref.store %10, %4[%arg1, %arg2, %arg3, %arg4] : memref<1x1x1x32xf32, strided<[160, 160, 160, 1], offset: ?>>
              }
            }
          }
        }
      }
    }
    scf.for %arg1 = %c0 to %c1 step %c1 {
      scf.for %arg2 = %c0 to %c1 step %c1 {
        scf.for %arg3 = %c0 to %c1 step %c1 {
          scf.for %arg4 = %c0 to %c32 step %c1 {
            %6 = memref.load %4[%arg1, %arg2, %arg3, %arg4] : memref<1x1x1x32xf32, strided<[160, 160, 160, 1], offset: ?>>
            %7 = arith.divf %6, %cst_0 : f32
            memref.store %7, %4[%arg1, %arg2, %arg3, %arg4] : memref<1x1x1x32xf32, strided<[160, 160, 160, 1], offset: ?>>
          }
        }
      }
    }                    
```

I might be missing something but I think we should be able to vectorize this pool operation by just lowering it to `linalg.generic` ops. I don't think it would be worth adding a specific vectorization pattern for pooling, at least for the "direct" approach. I would only worry more about pooling ops' performance when they move up in the profiles.

What are your thoughts? Do we currently have a way to lower pool ops to generic ops?

Thanks!

**Comment by hanhanW** [comment]
> I think we should be able to vectorize this pool operation by just lowering it to linalg.generic ops

There is a pass called `linalg-generalize-named-ops` that convert a named op to a generic op. However, the vectorization won't happen because there are strides and symbols in indexing_maps. We might have to apply what we've done in convolution vectorization -- tile some dimension with 1 and make the indexing_maps more pure (i.e., remove those strides/symbols from indexing maps).

IMO, this is a P2 issue. We know the issue for a long time, but we never prioritize the work. Because it is only maybe 2% in e2e performance latency. I think the basic lowering (i.e., linalg -> scf loops) can cover most of needs.

**Comment by dcaballe** [comment]
Thanks, Hanhan! I'm not familiar with this limitation. Could you help me understand? The maps look simple to me, only symbols and dims. They don't even fall into the semi-affine classification. The strides of the contiguous dimensions are also one so it should be easy to vectorize at least those dims. Is this a limitation of indexing maps in linalg generic?

> IMO, this is a P2 issue. We know the issue for a long time, but we never prioritize the work. Because it is only maybe 2% in e2e performance latency. I think the basic lowering (i.e., linalg -> scf loops) can cover most of needs.

I agree with the P2 prioritization but I think it might have more impact than 2%. Note that fusion is also not happening for the producers and the consumers of the pooling result. In this case, perhaps, it doesn't matter much since most of the outer loops only have one iteration but there could be other cases where that is not the case.

**Comment by hanhanW** [comment]
Here is the current limitation. Maybe there are some conditions could be relaxed: https://github.com/llvm/llvm-project/blob/d3b0e745e8a3ead8cc2f0cc246c19c13f0c35ebb/mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp#L555-L596

The main one for pooling ops is that it requires `allIndexingsAreProjectedPermutation`. However, we have windows in the pooling ops. Let's take the example from. the model:

Say that we have the pooling op:

```mlir
linalg.pooling_nhwc_sum {dilations = dense<1> : vector<2xi64>, strides = dense<33> : vector<2xi64>} ins(%6, %2 : memref<1x33x33x32xf32, strided<[174240, 5280, 160, 1], offset: ?>>, memref<33x33xf32>) outs(%5 : memref<1x1x1x32xf32, strided<[160, 160, 160, 1], offset: ?>>)
```

After we generalize it to a generic op:

```mlir
#map1 = affine_map<(d0, d1, d2, d3, d4, d5) -> (d4, d5)>
#map2 = affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d2, d3)>
#map6 = affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1 * 33 + d4, d2 * 33 + d5, d3)>
linalg.generic {
  indexing_maps = [#map6, #map1, #map2],
  iterator_types = ["parallel", "parallel", "parallel", "parallel", "reduction", "reduction"]}
  ins(%6, %2 : memref<1x33x33x32xf32, strided<[174240, 5280, 160, 1], offset: ?>>, memref<33x33xf32>)
  outs(%5 : memref<1x1x1x32xf32, strided<[160, 160, 160, 1], offset: ?>>) {
^bb0(%arg1: f32, %arg2: f32, %arg3: f32):
  %7 = arith.addf %arg3, %arg1 : f32
  linalg.yield %7 : f32
}
```

The map6 is not projected permutation, so the generic vectorization won't work here.

The next question is what we can do? IMO, the idea is implementing something like direct convolution vectorization.

1. We downsize the op by tiling either H dimension or W dimension with value 1, then we'll get a 1d pooling op. (this is for maintaining less vectorization patterns.)

2. Have a special vectorization logic for pooling op (maybe it's similar to the convolution one), which lowers the op to vector.reduction_min/max/sum.

The design doc is shared internally, I'm not sure if there is a public version. @antiagainst had another blogspot in his blog, which explains the ideas: https://www.lei.chat/posts/codegen-performant-convolution-kernels-for-mobile-gpus/

**Comment by dcaballe** [comment]
Thanks for the analysis, Hanhan! I have a much better picture now.

I think I would only go with #2 if there is a strong performance justification because providing op specific vectorization patterns don't scale very well. Most importantly, IMO, I think we have to tackle the fundamental problem here: I we don't have any representational limitation at `linalg.op` level, I don't see a reason why we shouldn't vectorize a memory access pattern with strides, especially when the stride for the FVD is one. That would help with pooling and convolution ops and hopefully with more operations in the future.

**Comment by hanhanW** [comment]
> That would help with pooling and convolution ops and hopefully with more operations in the future.

It would be great if we can factor out the needs for vectorizing pooling and convolution ops, and see if we can make it an interface. :-)

**Comment by dcaballe** [comment]
Thanks, Hanhan. That should work! However, I don't think tiling by 1 should be mandatory. This is just a multi-dimensional strided access that we should support in the vectorizer, even more when the FVD has a stride one. Dims with strides > 1 would only impact unrolling for this case. Even if the FVD had a stride > 1, that memory access should be lowered to a strided vector load that we could represent, in the worst case scenario, with a gather.

**Comment by allieculp** [comment]
@vmurali Stale issue here - is this still open?

**Comment by vmurali** [comment]
Not sure what this issue is; perhaps @dcaballe can verify? I did fix the vectorization of pooling ops in general.

**Comment by hanhanW** [comment]
This should be fixed by https://github.com/openxla/iree/pull/11710 and https://github.com/openxla/iree/pull/11822 closing the issue
