### ISSUE TITLE
[spirv] Drop usage of `linalg::tileProducerAndFuseConsumerLinalgOp`. Use `scf::tileConsumersAndFuseProducersGreedily`.

### ISSUE THREAD

**Issue by MaheshRavishankar** [openxla/iree#10724]
The `linalg::tileLinalgOp` and `linalg::tileProducerAndFuseConsumerLinalgOp`s are on deprecation path. There is only a single use of this in IREE, in the `SPIRVTile.cpp` file (see #10706 ). Please deprecate that method. The code for these methods have been moved from upstream into IREE to satisfy this dependence. This can be deleted after the switch is made.

**Comment by antiagainst** [comment]
This is done now.
