### ISSUE TITLE
[spirv] Add shared memory promotion for convolution

### ISSUE THREAD

**Issue by nirvedhmeshram** [openxla/iree#10749]
Right now the direct convolution CodeGen path only tiles and vectorizes convolution. For desktop/server GPU, we could also consider promoting the tiled filter slice into shared/workgroup memory so that we can gain faster access. 

This is the high level plan:

- Modify the `SPIRVBaseVectorizePassPipeline` to have shared memory promotion. For working on tensor semantics, the flow is similar to what we have for matmul in CUDA land. Basically after tiling to workgroups, we prmote (related [code](https://github.com/iree-org/iree/blob/40c0b11/compiler/src/iree/compiler/Codegen/LLVMGPU/LLVMGPUTensorAlloc.cpp#L99) and [tests](https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/LLVMGPU/test/tensor_alloc.mlir)) the filter using `bufferization.alloc_tensor`, and then perform further tiling to threads and following steps. 
- There is concerns about large buffers being made that exceeding the shared/workgroup memory limit, since this is done before tiling reduction dimension (to avoid difficulties around promoting after). So we need to be conservative and compute the amount of shared memory needed to make sure it does not go beyond max compute workgroup invocations from target environment. Typically FH/FW is 3 so this is meanly OC and IC for the filter. IC can be large. It also mean we may need to adjust how we tile along OC dimensions to make it small.

**Comment by antiagainst** [comment]
Closing this as obsolete.
