### ISSUE TITLE
Reconsider `DecomposeLinalgGenericPass` in `--iree-vmvx-enable-microkernels`

### ISSUE THREAD

**Issue by bjacob** [openxla/iree#10813]
At the moment, `--iree-vmvx-enable-microkernels` enables a `DecomposeLinalgGenericPass` here: https://github.com/iree-org/iree/blob/2765a69263110b3ad181362a9ff448fe88215928/compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp#L424

I understand that was motivated by matching simple Generics to simple microkernels.

But as we enable `--iree-vmvx-enable-microkernels` on more tests, we discover downsides of that:

- Intermediate buffers are necessary between the multiple generics that a complex generic is decomposed into. Even though `DecomposeLinalgGenericPass` is run just before bufferization and only creates `tensor.empty`, during bufferization the `EmptyTensorLoweringPattern` turns those into `bufferization.alloc_tensor` and they eventually become `memref.alloca`, and we fail with: `error: failed to legalize operation 'memref.alloca' that was explicitly marked illegal`.
  - Testcase + repro in https://gist.github.com/bjacob/8538553b3f29763941da7c41bf008472

- Is splitting generics really beneficial? While it creates opportunities to match some simple generics with simple ukernels, it removes other opportunities to match some (less simple) other generics with (less simple) ukernels, and until we prove we're able to match all the tiny generics with ukernels, we can easily be worse off than with a single generic going down the default VM path. Here we are talking about going down to one operation in the basic-block. How many things can be expressed as linalg.generic with only one op in the basic block?
  - Consider a `i8*i8->i32` element-wise multiplication. It would be 2 `arith.extsi` sign-extending the `i8` inputs to `i32`, followed by a `arith.muli`.  We would be splitting it into 3 generics, going through `i32` temporaries, removing the opportunity to match that with a ukernel using native  `i8*i8->i32` instructions.
  - Where `DecomposeLinalgGenericPass` goes really extreme is when a `linalg.generic` does any `index` arithmetic. Consider this test code populating a 2D array with incrementing integer elements: https://github.com/iree-org/iree/blob/2765a69263110b3ad181362a9ff448fe88215928/tests/e2e/linalg_ext_ops/pack.mlir#L1-L16 `DecomposeLinalgGenericPass` decomposes that into separate generic ops for each individual `arith` op on `index` values here, creating temporary `memref<?x?xindex>`. This actually causes assertion failures in some existing code that wasn't expecting an element type to be `index` (e.g. `type.isIntOrFloat` returns `false` on `index`). Having that fixed in #10814 I'm back to asking: is that really what we want to be doing.

In #10798 I have to introduce a `--iree-vmvx-enable-microkernels-decompose-linalg-generic` flag, defaulting to `true` for the current behaviour, so I can set it to `false` in those tests that have nontrivial generics.

Options:

1. Keep `DecomposeLinalgGenericPass` on by default.
2. Change the default value of `--iree-vmvx-enable-microkernels-decompose-linalg-generic` to `false`  (so we would retain the option to pass `true` if we really want it on some case, to retain the ease of experimenting for now).
3. Drop `DecomposeLinalgGenericPass` altogether from `--iree-vmvx-enable-microkernels`.

Musings:

- Maybe splitting generics to some fine granularity is a good idea for *some* fine granularity, just not down to one single op in the generic's block.
- Maybe the bind we're in here really tells us that what we want is codegen+ukernels, not vmvx+ukernels. VMVX is being a useful vehicle for early ukernel work but when we get to a level of detail where we worry about every remaining generic not matching a ukernel, that could be the sign that we should refocus performance effort on codegen and leave VMVX+ukernel with lesser performance. It would still be better than VMVX with no ukernel at all, it could still be a great alternative perf/portability tradeoff vs codegen, and users who need higher performance for VMVX+ukernel for a specific case could still add more ukernels, even matching a complex generic if needed, for their use case. In fact, such people would *prefer* not decomposing linalg generics at all.

**Comment by bjacob** [comment]
Assigned to @stellaraccident to get a decision / also tagging @MaheshRavishankar , @benvanik .

**Comment by bjacob** [comment]
OK. I'm not blocked, now that #10798 is merged and added `--iree-vmvx-enable-microkernels-decompose-linalg-generic`, effectively allowing me to opt out from this on a case by case basis while this gets resolved either way.

**Comment by MaheshRavishankar** [comment]
I think in fullness of time decomposition is useful. I wrote it as an intermediate before vectorization. That path is unexplored. Final state AFAICS is,

1) have tensor representation of operations that lower to microkernels. Also adds hooks to bufferization to connects from these ops to the ops that work on buffers today. 
2) after tiling, lower to these tensor ops first
3) do decomposition
4) vectorize.
5) bufferize.

That should account for intermediate allocations but might lead to high register usage. So depends on the trade off there. But on vmvx path we should still be able to do this without any intermediates.
