### ISSUE TITLE
Segfault compiling e2e/regression/lowering_config.mlir test on Windows

### ISSUE THREAD

**Issue by ScottTodd** [openxla/iree#11068]
`iree-compile --iree-input-type=mhlo --iree-hal-target-backends=llvm-cpu tests/e2e/regression/lowering_config.mlir` crashes with a segfault on Windows.

Spotted when adding a Windows CI build: https://github.com/iree-org/iree/actions/runs/3397642741/jobs/5649990603, and then reproduced locally.

When run under a debugger, I'm _not_ seeing a breakpoint get hit, or a stacktrace, just this error logged:
```
LLVM ERROR: IO failure on output stream: invalid argument
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
```

The last pass to run is `// -----// IR Dump After mlir::iree_compiler::IREE::VM::OrdinalAllocationPass (iree-vm-ordinal-allocation) //----- //`: https://gist.github.com/ScottTodd/d971ab4e10fa73ebedbc35789921f67b

So maybe crashing in here: https://github.com/iree-org/iree/blob/e64babedb0bb323d5ff29c3b0b535ae0eff677a9/compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.cpp#L228-L239

**Comment by ScottTodd** [comment]
I'm seeing this code path: https://github.com/llvm/llvm-project/blob/129177eaf0ecb202a6f44ab8d23ad51fe00d15f6/llvm/lib/Support/raw_ostream.cpp#L685-L700

Are there unicode characters in the output that we don't generate in other tests?

**Comment by ScottTodd** [comment]
> weiiird, can you find where we open that path in a debugger and see what the memory contents are? maybe a missing nul terminator on the string?

Tried that, didn't see much interesting :/

**Comment by MaheshRavishankar** [comment]
Lowering config is just supposed to help with the compilation. So if there is no issue with executable translation here then I dont think there is a problem with lowering config as such... Happy to help more (feel free to re-assign), but I dont have a windows build....

**Comment by ScottTodd** [comment]
This appears to be fixed now, at least on my local machine. I'll send a PR that re-enables the test on CI.
