### ISSUE TITLE
Update CI environment to Python 3.8

### ISSUE THREAD

**Issue by pzread** [openxla/iree#11087]
Python 3.7 is the current minimum supported version in IREE, which will be EOL in 7 months (27 Jun 2023). Update the CI environment to 3.8 after that date.

Although there is still a bunch of time before the EOL of 3.7, filing this issue to track the update task as we are waiting for some Python 3.8 features (e.g. #11073).

Changes that have related TODOs:

- [x] #11073

**Comment by jpienaar** [comment]
Related issue seems to have been completed, is anything pending here?

**Comment by pzread** [comment]
There are some TODOs can be cleanup. I'll do it.
