### ISSUE TITLE
Custom mmt4d path is broken in fusion dispatch cases - low priority

### ISSUE THREAD

**Issue by hanhanW** [openxla/iree#11165]
This is a P2 bug, and we'll prioritize the bug after bringing up data tiling path. In the new pipeline, the linalg.mmt4d op will live in its own dispatch for a while. Because there is an unpack op right after the mmt4d op. We'll have to handle the case after propagating pack/unpack op and folding them away.

What's happening on ToT:

The tile+fuse pass takes `[1, 1, 0, 1, 8, 0]` as tiling sizes. However, the inner tile sizes are set to 1s. It's not `1x8x1` mmt4d cases anymore, so the custom kernel pass does not work. The inner tile size should be `1x8x1` after tile+fuse. Something goes wrong in the pass. IR dump: https://gist.githubusercontent.com/hanhanW/e0ccd106ed5fdbacfad7e0f77bf2ae46/raw

To repro:

```mlir
func.func @foo(
    %16: tensor<1x2048x1x1xf32>, %17: tensor<64x2048x8x1xf32>,
    %18: tensor<1x64x1x8xf32>, %19: tensor<1x64x1x8xf32>,
    %20 : tensor<f32>) -> tensor<1x64x1x8xf32> {
  %cst = arith.constant 5.000000e-01 : f32
  %cst_0 = arith.constant 0.000000e+00 : f32
  %c665984 = arith.constant 665984 : index
  %0 = hal.interface.constant.load[0] values([676608 : i32, 1154944 : i32, 1155008 : i32, 1156992 : i32, 1161088 : i32, 1163136 : i32]) : i32
  %1 = hal.interface.constant.load[1] values([659072 : i32, 1140608 : i32, 1142656 : i32, 1146752 : i32, 1148800 : i32]) : i32
  %2 = hal.interface.constant.load[2] : i32
  %3 = hal.interface.constant.load[3] : i32
  %4 = hal.interface.constant.load[4] values([661120 : i32, 1142656 : i32, 1144704 : i32, 1148800 : i32, 1150848 : i32]) : i32
  %5 = arith.index_castui %0 : i32 to index
  %6 = arith.index_castui %1 : i32 to index
  %7 = arith.index_castui %2 : i32 to index
  %8 = arith.index_castui %3 : i32 to index
  %9 = arith.index_castui %4 : i32 to index
  %21 = tensor.empty() : tensor<1x64x1x8xf32>
  %22 = linalg.fill ins(%cst_0 : f32) outs(%21 : tensor<1x64x1x8xf32>) -> tensor<1x64x1x8xf32>
  %23 = linalg.mmt4d {comment = "f32*f32->f32, aarch64, narrow matrix * matrix, where the narrow matrix has 1 column(s)"} ins(%16, %17 : tensor<1x2048x1x1xf32>, tensor<64x2048x8x1xf32>) outs(%22 : tensor<1x64x1x8xf32>) -> tensor<1x64x1x8xf32>
  %24 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> ()>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%18, %23, %19, %20 : tensor<1x64x1x8xf32>, tensor<1x64x1x8xf32>, tensor<1x64x1x8xf32>, tensor<f32>) outs(%21 : tensor<1x64x1x8xf32>) {
  ^bb0(%in: f32, %in_1: f32, %in_2: f32, %in_3: f32, %out: f32):
    %25 = arith.addf %in_1, %in_2 : f32
    %26 = arith.mulf %25, %in_3 : f32
    %27 = arith.mulf %26, %cst : f32
    %28 = arith.addf %in, %27 : f32
    linalg.yield %28 : f32
  } -> tensor<1x64x1x8xf32>
  return %24 : tensor<1x64x1x8xf32>
}
```

**Comment by benvanik** [comment]
> The linalg.mmt4d op will live in its own dispatch.
That feels wrong? We should definitely be fusing the generics with the mmt4d.

**Comment by hanhanW** [comment]
There will be an unpack op right after the mmt4d op, and I thought the fusion of linalg.mmt4d + unpack will not happen?

After thinking a while, I found that you're also right, because the unpack could be folded away with a consumer pack op.

**Comment by benvanik** [comment]
Yep! We want to (effectively) sink unpacks as far as we can across elementwise ops and anything else we can such that they can either eliminate each other or avoid introducing new dispatch regions that do full reads/writes.

**Comment by hanhanW** [comment]
Yes! let me update the content of the issue a bit.

**Comment by benvanik** [comment]
(sorry for the drive-by - just waiting for water to boil and skimming issues :)

**Comment by hanhanW** [comment]
(it's always good that we have more eyes on it. :D)

**Comment by hanhanW** [comment]
This is no longer an issue, can not reproduce it today.
