### ISSUE TITLE
Integrate new side effect modeling

### ISSUE THREAD

**Issue by GMNGeoffrey** [openxla/iree#1124]
MLIR now has improved side effect modeling which allows us to differentiate different types of side effects. Concretely, this allows something like tagging an alloc up in such a way that it will undergo DCE, but not CSE. Investigate adding this to IREE IRs

**Comment by benvanik** [comment]
https://github.com/iree-org/iree/issues/9242#issue-1251376607 has some updated info

**Comment by GMNGeoffrey** [comment]
Side effect modeling has not been new for a few years now. I think we have incorporated it
