### ISSUE TITLE
Stream/IR/test:timepoint_folding.mlir.test is timeout after integrates

### ISSUE THREAD

**Issue by hanhanW** [openxla/iree#11251]
The test will be disabled in https://github.com/iree-org/iree/pull/11245

**Comment by allieculp** [comment]
@benvanik Doing a Github clean up scrub again.. Any priority / status here?

**Comment by benvanik** [comment]
High priority as this is covering important stuff but if anyone else is available to at least perform basic triage that'd be helpful. This is (hopefully) just canonicalizer/folder behavior changes.
