### ISSUE TITLE
test/e2e/matmul:e2e_matmul_direct_f32_large_split_k_cuda_cuda.mlir.test numerical errors after integrate #11275

### ISSUE THREAD

**Issue by KoolJBlack** [openxla/iree#11281]
Test was disabled in https://github.com/iree-org/iree/pull/11275

Failure: https://github.com/iree-org/iree/actions/runs/3534720400/jobs/5932099402#step:7:334

**Comment by ThomasRaoux** [comment]
@vmurali could you check if this is related to your recent changes?

**Comment by vmurali** [comment]
@ThomasRaoux is there a way to generate that test with the correct config? It seems I need to use `generate_e2e_matmul_tests.py` with specific parameters to generate it. Moreover, is there a Cuda system I can run it on?

**Comment by ThomasRaoux** [comment]
> @ThomasRaoux is there a way to generate that test with the correct config? It seems I need to use `generate_e2e_matmul_tests.py` with specific parameters to generate it. Moreover, is there a Cuda system I can run it on?

You can use a the GCP instance we have, you can use mine and ssh into it. There is a command line to run only the tests you want in `generate_e2e_matmul_tests.py` I believe there is some doc for it.

**Comment by vmurali** [comment]
https://github.com/iree-org/iree/pull/11431 should fix this. I can close this once that PR lands.
