### ISSUE TITLE
Numerics issue with microsoft/mpnet-base model in SHARK (mhlo/cpu)

### ISSUE THREAD

**Issue by monorimet** [openxla/iree#11446]
### What happened?

AssertionError: 
Not equal to tolerance rtol=0.01, atol=0.001

Mismatched elements: 58 / 3907456 (0.00148%)
Max absolute difference: 0.00209427
Max relative difference: 823.08344
 x: array([[[40.38997 ,  4.286407, 23.762331, ..., -1.074988, -0.482311,
         16.880703],
        [ 2.257947,  0.504235,  8.199038, ..., -1.836042,  0.471552,...
 y: array([[[40.389954,  4.286396, 23.76234 , ..., -1.074993, -0.482318,
         16.880716],
        [ 2.257939,  0.504236,  8.199036, ..., -1.836042,  0.47155 ,...

### Steps to reproduce your issue

Reproducers are available [here](https://console.cloud.google.com/storage/browser/shark-public/builder/repro_artifacts/bb8f/microsoft_mpnet-base_tf_False_cpu).

**Comment by benvanik** [comment]
(here's another one where you're veeery close to your cutoff - I'm not sure anyone on the IREE side is going to be able to do much with these reports as-is)

**Comment by MaheshRavishankar** [comment]
I initially thought that maybe we are doing associative reordering by default in IREE CPU, but turns out we are not.... How do we know that the baseline is not with associative reordering?

**Comment by MaheshRavishankar** [comment]
FYI @vmurali nothing to do yet, but just tagging you to follow along

**Comment by benvanik** [comment]
(I'm not great at these kind of issues, but just guessing what someone would want to know: what are you comparing against? what exactly are the flags/settings/etc it is using? (for example some ML frameworks use lower precision, fastmath, etc by default) what's acceptable assuming bit-exact floating point through a whole model is impossible? etc)

**Comment by hanhanW** [comment]
How does the golden value come from? I'm afraid that it's an issue similar to https://github.com/iree-org/iree/issues/9853, which enables some fancy optimization when generating golden values. If this is the case, there are nothing to do on IREE side..

**Comment by MaheshRavishankar** [comment]
tensorflow by default uses associative reordering. So we will be hard pressed to match that accurately.

**Comment by hanhanW** [comment]
> we have tensorflow configured to cpu only when generating the artifacts.

This does not imply that fancy optimizations are not kicked in, could you figure a way generating real golden values?

In the meantime, I think @vmurali can try if the results between VMVX and LLVM-CPU are close enough or not. If they are not close, we might have numerical issues on CPU side.

**Comment by benvanik** [comment]
Agreed with changing tolerances where it's acceptable - the problem with comparing against other optimizing frameworks is that we risk disabling their optimizations and hurting our ability to optimize ourselves as we are comparing against a reference implementation _or_ hurting our accuracy by comparing against their own arbitrary mix of optimizations that isn't really the "right" number - the safest position is to compare against what a user expects and relax the tolerances in any particular pairwise comparison to capture that. It's hard for us to decide what a user would expect from a particular model though ;(

**Comment by hanhanW** [comment]
I see, good points! Relaxing the tolerances makes sense, but yeah.. we'll need someone to decide the values for each model..

**Comment by hanhanW** [comment]
Maybe we can simply relax the tolerances if the results between VMVX and llvm-cpu are close enough (like within 1e-6), since we don't do associative reordering on both sides.

**Comment by jpienaar** [comment]
Any work left here?
