### ISSUE TITLE
bazel test ... results in failures on transform_dialect/cuda/ on machines without GPU

### ISSUE THREAD

**Issue by jpienaar** [openxla/iree#11560]
`bazel test ...` fails as these tests expect to run on machines with GPUs/where cuda target is registered.

**Comment by GMNGeoffrey** [comment]
Can you elaborate on what failure you see. I just got a crash when importing this into Google's monorepo and reopened https://github.com/iree-org/iree/issues/11560, but maybe it's the same as this issue.

**Comment by jpienaar** [comment]
Oh in my case it just fails due to no CUDA device in system and so backend isn't registered.

**Comment by allieculp** [comment]
@jpienaar Wondering if this is still open..?

**Comment by jpienaar** [comment]
I'm not sure, there were a few big refactorings post. @sushreebarsa may be able to help verify

**Comment by ScottTodd** [comment]
This issue looks stale and may be a duplicate of https://github.com/openxla/iree/issues/15233.

I don't think `bazel test ...` without filtering is expected to pass on machines that don't have support for all hardware / configurations (some of which may be mutually exclusive)
