### ISSUE TITLE
Remove the need for `encoding` attributes on `pack` ops

### ISSUE THREAD

**Issue by bjacob** [openxla/iree#11608]
In #11603 we started copying the tensor `encoding` attributes onto the `pack` op created in `MaterializeEncoding`.  That was only needed for one pattern, `LowerDispatchWorkgroupCountFromSetEncodingOp`, which runs later (`TileAndDistributeToWorkgroups`) and needs to evaluate dynamic tile sizes because it needs to know outer sizes, which depend on those tile sizes (as a quotient).

What's the long-term fix? @MaheshRavishankar  (not urgent, when you come back), @hanhanW

**Comment by allieculp** [comment]
@MaheshRavishankar Setting this as a P2 'needs scheduling' - please edit as needed.

**Comment by MaheshRavishankar** [comment]
#13038 should fix this.
