### ISSUE TITLE
FR: Don't run workflows requiring GPUs on forks

### ISSUE THREAD

**Issue by jpienaar** [openxla/iree#11619]
### Request description

Similar to https://github.com/iree-org/iree/tree/main/.github/workflows/schedule_candidate_release.yml we could avoid running SHARK, mmperf and convperf on forks by default. These all require GPU runners and end up producing a lot of emails in forks/action failures or repeated usage of resources.

### What component(s) does this issue relate to?

Other

**Comment by GMNGeoffrey** [comment]
You can disable specific workflows or actions entirely at the repository level. I don't think hardcoding the repository name is really the best way to do this.

**Comment by ScottTodd** [comment]
Yeah, I don't think we can do much here, beyond educate developers about GitHub's built-in features for disabling workflows in forks.
