### ISSUE TITLE
Avoid unnecessary padding in `iree-flow-set-encoding`

### ISSUE THREAD

**Issue by bjacob** [openxla/iree#11632]
(Updated July 2023)

When data-tiling, during Flow we don't know yet the exact tile sizes, so we don't know yet exactly how much padding is needed to ensure that buffers are allocated large enough to account for padding to the next multiple of what will be the actual tile size.

The current code is simply using a hardcoded tile size of 16, along every dimension, in Flow.

Problems with that:
1. That's assuming that no tile size will ever be larger than 16, which is not a safe assumption with ever-wider SIMD. Intel AMX, Apple AMX, ARM SME, SiFive (RISC-V) Intelligence extensions are all defeating that. In fact, with narrow data types such as `float16`, even AVX-512 or ARM SVE or RISC-V RVV can already defeat that with tile sizes equal to 32. So _resolving that blocks being able to target all these near-team SIMD targets_.
2. When the matrix shapes are very narrow, meaning that some dimension size is less than 16, padding to the next multiple of 16 can be large overhead. Particularly for matrix-times-vector multiplications, the widening is from 1 to 16 columns, immediately rephrasing the problem at hand into one that involves 16x more arithmetic.
3. Incomplete tiles are costly to deal with in packing code. We would normally have at most one incomplete tile at the end of each dimension, but because of this, we can have as many as 16.
4. This requires the `SetEncoding` pass to be parametrized in a `defaultPadding` option, while it could otherwise be unparametrized.

**Comment by MaheshRavishankar** [comment]
I would need @benvanik s suggestions on it. I am passing this to him for the time being

**Comment by bjacob** [comment]
Tentative fix: https://github.com/openxla/iree/pull/14349
