### ISSUE TITLE
Support mhlo.rng_bit_generator

### ISSUE THREAD

**Issue by okkwon** [openxla/iree#11761]
### Request description

The instruction appears in some of my models I am trying to support.

Here is the API spec: https://www.tensorflow.org/mlir/hlo_ops#mhlorng_bit_generator_mlirmhlorngbitgeneratorop

This needs to be lowered into linalg or other op first.

### What component(s) does this issue relate to?

Frontends

**Comment by jpienaar** [comment]
Coordinating with others looking in this area.

**Comment by rsuderman** [comment]
Landed the ThreeFry work on the mlir-hlo side:
https://github.com/tensorflow/mlir-hlo/commit/516b9f7b9989e778e619980c54eb269c0fb6fede

Philox is still a WIP

**Comment by jpienaar** [comment]
@jvstokes FYI

**Comment by phoenix-meadowlark** [comment]
`mhlo.rng_bit_generator` is used in PAX's variable initialization (on both the training and evaluation paths), so we'll need to support it in order to use IREE+PJRT with PAX models (e.g. to test multi-device execution).

**Comment by julianwa** [comment]
@phoenix-meadowlark do you have any workarounds in the meantime?

**Comment by jpienaar** [comment]
Easiest workaround is using ThreeFry instead of Philox, the former is already implemented and the latter is almost done.

**Comment by rsuderman** [comment]
@jvstokes solution works for most case, logging as fixed
