### ISSUE TITLE
Some models run slower on Ubuntu 22.04 than Ubuntu 20.04

### ISSUE THREAD

**Issue by pzread** [openxla/iree#11884]
Some models seem to always run slower (+15%) on Ubuntu 22.04 (kernel `5.15.0-1025-gcp`) than Ubuntu 20.04 (kernel `5.15.0-1027-gcp`) with the same machine spec (`GCP c2-standard-16`).

Comparison table: https://gist.github.com/pzread/40aac29290de29ef465692616015fba4 @ 55fa553347ae1d9cd928ad3a120e7e3e7822f53a (base is 20.04 and target is 22.04)

Sample trace of `MiniLML12H384Uncased-int32,seqlen128` with local-sync
https://storage.googleapis.com/iree-jerry-test/iree-11884/minilm-sample.tar.gz

**Comment by pzread** [comment]
Linux benchmarks on https://perf.iree.dev moved to Ubuntu 22.04 since https://github.com/iree-org/iree/commit/1290401bd7c02c4ac35d5689c278d9c32665e6a0.

The regressions we found here are now shown on the perf dashboard. For example:
https://perf.iree.dev/serie?IREE?232dd191f613b7aebb8501342bf8c99afd519e1554b234d797e6aef3779066a7
![image](https://user-images.githubusercontent.com/2104162/219511852-e64da850-2900-4e50-b96f-51632fb1c8a1.png)

**Comment by allieculp** [comment]
@benvanik Curious if you ever reviewed this? Should we prioritize?

**Comment by ScottTodd** [comment]
I'm not sure if this is worth investigating at this point. Close as stale?
