### ISSUE TITLE
transform dialect switch causes a regression

### ISSUE THREAD

**Issue by sogartar** [openxla/iree#11991]
### What happened?

The change fafde8723 causes one [test](https://github.com/iree-org/iree-jax/pull/43) that I have submitted for a review to IREE Jax to fail.
It is the CUDA test `MnistTrainTest.test_train_mnist_cuda`. It verifies that a training step update does the same thing in IREE as in Jax. There is a significant loss of accuracy.

### Steps to reproduce your issue

If you want to run the test you will need to install the CPU version of Jax. Version 0.4.2 at least.

### What component(s) does this issue relate to?

MLIR, Compiler

### Version information

fafde8723

### Additional context

The test is marked as xfail because I have not decided if the initialization of the weights should produce an exact result or an approximate one, but the other assertions before that should pass.

**Comment by nicolasvasilache** [comment]
how can we repro this ?

**Comment by sogartar** [comment]
I will isolate Jax and get the input MLIR together with fixed values and make a auto test with them.

**Comment by Young768** [comment]
Hi @sogartar how can I access the data so I can reproduce this issue from my side(NV)? Thanks
```
DIGEST="$(sha256sum mnist_train.tar | awk '{print $1}')"
gcloud storage mv mnist_train.tar "gs://iree-model-artifacts/mnist_train.${DIGEST}.tar"
```

**Comment by jpienaar** [comment]
I think here you can patch in the PR and then follow  https://github.com/openxla/iree/blob/c9d528ffdbae5d152be4cfb2dce12c9c4950ea27/tests/e2e/models/mnist_train_test/README.md to generate

**Comment by allieculp** [comment]
@Young768 Is there any update on this issue?

**Comment by Young768** [comment]
@allieculp I was able to reproduce the accuracy issue on GPUs and trying to locate which transform dialect causes the issue.

**Comment by Young768** [comment]
@jpienaar Hi It looks like this [transform dialect ](https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/Common.cpp#L422-L456) on linalg.generic op failed the test.
If I skipped the linalg.generic op, the test passed. Could you please provide some guideline on how to fix this or what does this transform dialect do?

**Comment by jpienaar** [comment]
@hanhanW or @ftynse would know best. To make sure I understand, if you apply this transform then there is a large regression else you get the accuracy expected?

**Comment by Young768** [comment]
@jpienaar Yes. More specifically, ```ReductionStrategy::Small``` on ```linalg.generic``` caused the regression.

**Comment by jpienaar** [comment]
How large are the numerical differences? Is this dynamic or static op?

@nicolasvasilache would also know this strategy but don't think he'll have time to respond now.

**Comment by Young768** [comment]
@jpienaar It exceeds 1e-5. Btw, how can I know a ```linalg::LinalgOp``` is dynamic or static?

**Comment by jpienaar** [comment]
What is the relative error? (I'm assuming that is absolute). Just check the dimensions on the op, if you see an unknown dimension (`?`) then dynamic [I was looking at the code and saw dynamic ones are treated as small, it may be completely unrelated but I wasn't sure why small was being selected here]

**Comment by nicolasvasilache** [comment]
If there is an isolated op / test i can use to easily repro I can give it a shot tomorrow. Otherwise I'll have to pick this up in 2 weeks.

**Comment by Young768** [comment]
Yes, thats absolute error. I checked it is static op. @jpienaar 

@nicolasvasilache The op is ```linalg.generic``` with size of 2 operandTypes(), ```tensor<128x10xf32>```  ```tensor<128xf32>```
do you need more info?

**Comment by nicolasvasilache** [comment]
> do you need more info?

Some input IR file with constant values filled in and an iree command to run and check the result against the values you expect would be needed to be sure of what happens with expected precision: fp is not associative.

The small reduction strategy is simple, it performs reductions sequentially in each thread.
It does perform a vector<4> load/compute per thread and I conjecture these partial accumulations may be changing the precision wrt what is expected.

Can you try this patch: https://github.com/openxla/iree/pull/13225 ?
It disables partial accumulations for the small case and just iterates over values sequentially.

Also @qcolombet

**Comment by Young768** [comment]
@nicolasvasilache That patch does not fix the issue.

**Comment by Young768** [comment]
@nicolasvasilache I think the problem is the trailing part, not the reduction part.
Either commenting out these [lines](https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.cpp#L143-L152), 
or applying the patch to the trailing part:
```
auto res = iree_compiler::buildTileFuseToScfFor(
      /*b=*/b,
      /*isolatedParentOpH=*/variantH,
      /*rootH=*/maybeBlockTrailingH,
      /*opsHToFuse=*/{},
      /*tileSizes=*/getAsOpFoldResult(b.getI64ArrayAttr({scfForTileSizes})));
```
the test passes. Specifically, the problem is this [branch](https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/Common.cpp#L258-L267), in which splitPoint: 0 vectorSize 1 numThreads: 128.
Since opsHToFuse.size = 0, (no fusion I guess?) I think we should use buildTileFuseToScfFor instead of buildTileFuseDistToForallWithNumThreads?

**Comment by MaheshRavishankar** [comment]
I am not fully aware of all the transformations being done here (Nicolas is on vacation). In the meantime if you could post the IR before and with/without the offending transform, I can take a look.

**Comment by Young768** [comment]
So I generated the [IR](https://gist.github.com/Young768/592db9f3c47e62eba5b233bbc827e97c). The diff.mlir is the difference between the failed and passed one. The difference in code is that if I comment out these [lines](https://github.com/Young768/iree/blob/main/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/Common.cpp#L247-L256), the test passed.

**Comment by MaheshRavishankar** [comment]
Sorry for the delayed response... So in the diff , the `-` is the passing or is the `+` passing?

**Comment by Young768** [comment]
I compared both the IR after ```iree-transform-dialect-interpreter``` pass. The only diffrence is with and without [iree_compiler::buildTileFuseDistToForallWithNumThreads](https://github.com/Young768/iree/blob/main/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/Common.cpp#L247-L256). Without these lines, the test passed.

**Comment by MaheshRavishankar** [comment]
> I compared both the IR after `iree-transform-dialect-interpreter` pass. The only diffrence is with and without [iree_compiler::buildTileFuseDistToForallWithNumThreads](https://github.com/Young768/iree/blob/main/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/Common.cpp?rgh-link-date=2023-05-04T21%3A15%3A45Z#L247-L256). Without these lines, the test passed.

I understand that, but I am trying to understand whats the before IR and whats the after.... The before IR looks more reasonable to me just reading it, the after seems strange, and not what I would expect...

**Comment by ftynse** [comment]
> Sorry for the delayed response... So in the diff , the - is the passing or is the + passing?

Looks like the - is passing and the + is not passing.

> The before IR looks more reasonable to me just reading it, the after seems strange, and not what I would expect...

The IR after seems to have mapped both dimension of the output memref to `threadIdx.x` somehow, and it look suspicious.

If we look at the subviews for the output, we see:

```mlir
%2 = affine.apply affine_map<()[s0] -> (s0 * 128)>()[%workgroup_id_x]
%3 = gpu.thread_id  x
%subview_1 = memref.subview %1[%2, 0] [128, 10] [1, 1] : memref<128x10xf32> to memref<128x10xf32, strided<[10, 1], offset: ?>>
%subview_3 = memref.subview %subview_1[%3, 0] [1, 10] [1, 1] : memref<128x10xf32, strided<[10, 1], offset: ?>> to memref<1x10xf32, strided<[10, 1], offset: ?>>

// %8 is 1 for 0 <= threadIdx.x < 10.
%8 = affine.min affine_map<()[s0] -> (-s0 + 10, 1)>()[%3]
// %9 is 1 for 0 <= threadIdx.x < 10 and 0 for all the others.
// This trick lets us create "empty" subviews and thus "mask out" linalg.generic's
// on some threads.
%9 = affine.max affine_map<()[s0] -> (0, s0)>()[%8]

// This subview has size 1x1 on the first 10 threads and 1x0 on the others.
%subview_5 = memref.subview %subview_3[0, %3] [1, %9] [1, 1] : memref<1x10xf32, strided<[10, 1], offset: ?>> to memref<1x?xf32, strided<[10, 1], offset: ?>>
```

I suppose we are mapping to 1 workgroup of 128 workitems, so `%2` is always 0. We can then compose the subviews.

```
%subview_5 = memref.subview %1[thread_id x, thread_id x][1, (0 or 1)*][1, 1]
// 1 for the first 10 threads, 0 for the others.
```

The trailing generic then writes to this subview. If I am not mistaken, it will thus write only the diagonal elements in the first 10 rows of the output and will ignore the rest.

The "before" code is writing entire rows:

```mlir
vector.transfer_write %11, %subview_1[%c0, %c0] {in_bounds = [true, true]} : vector<1x10xf32>, memref<1x10xf32, strided<[10, 1], offset: ?>>
```

I *suppose* the second dimension is erroneously mapped to `x` workitems and should have been mapped to `y` workitems (if they exist).

**Comment by ftynse** [comment]
Or alternatively the leading dimension should have been mapped, e.g.

```
+        %forall_op_9, %tiled_op_10 = transform.structured.tile_to_forall_op %rest_7   num_threads [0, 128] tile_sizes [](mapping = [#gpu.thread<x>])
```

should in fact be

```
+        %forall_op_9, %tiled_op_10 = transform.structured.tile_to_forall_op %rest_7   num_threads [128] tile_sizes [](mapping = [#gpu.thread<x>])

```

**Comment by ftynse** [comment]
@Young768 what does the IR look like _before_ the transform interpreter pass?

~I suspect that the rank of reduction is less than that of the trailing elementwise, which would lead to
https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.cpp#L138
and https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.cpp#L149
hitting different dimensions. This may be related to the `TODO` comments just above these lines.~

Scrap the above, one of the calls should be mapping to one thread. New suspicion: https://github.com/openxla/iree/blob/93781b36026b297bc6c42720a06ffcf55574568a/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.cpp#L111 uses `workgroupTileSizes` that are set to just `[128]` whereas https://github.com/openxla/iree/blob/93781b36026b297bc6c42720a06ffcf55574568a/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.cpp#L151 will map only the most minor dimension of the trailing computation, leading to the `[0, 128]` num threads configuration.

That being said, mapping trailing elementwise differently is okay, but seems to remain mapped similarly to the reduction so the mapping happens _twice_ for it.

**Comment by ftynse** [comment]
Looking at the transform script (it ended up being useful to this as script rather than functions calling each other), the trailing operation is indeed mapped twice to the same thread ID:

```mlir
	// leading, fill, reduction, trailing
        %0:4 = transform.iree.match_callback failures(propagate) "reduction"(%arg0) : (!pdl.operation) -> (!pdl.operation, !pdl.operation, !pdl.operation, !pdl.operation)
        // trailing, reduction
        %first, %rest = transform.iree.take_first %0#3, %0#2 : (!pdl.operation, !pdl.operation) -> (!pdl.operation, !pdl.operation)
        // loop, trailing
        %forall_op, %tiled_op = transform.iree.tile_to_forall_and_workgroup_count_region %first   num_threads [] tile_sizes [128](mapping = [#gpu.block<x>])
        transform.iree.apply_patterns %arg0 {canonicalization, cse, licm, tiling_canonicalization} : (!pdl.operation) -> ()
        // reduction
        %1 = transform.structured.fuse_into_containing_op %rest into %forall_op
        // fill
        %2 = transform.structured.fuse_into_containing_op %0#1 into %forall_op
        // leading
        %3 = transform.structured.fuse_into_containing_op %0#0 into %forall_op
        transform.iree.apply_patterns %arg0 {canonicalization, cse, licm, tiling_canonicalization} : (!pdl.operation) -> ()
        // reduction, trailing
        %first_0, %rest_1 = transform.iree.take_first %1, %tiled_op : (!pdl.operation, !pdl.operation) -> (!pdl.operation, !pdl.operation)
        // trailing, reduction
        %first_2, %rest_3 = transform.iree.take_first %rest_1, %first_0 : (!pdl.operation, !pdl.operation) -> (!pdl.operation, !pdl.operation)
        // loop, trailing
        %forall_op_4, %tiled_op_5 = transform.structured.tile_to_forall_op %first_2   num_threads [128] tile_sizes [](mapping = [#gpu.thread<x>])
        transform.iree.apply_patterns %arg0 {canonicalization, cse, licm, tiling_canonicalization} : (!pdl.operation) -> ()
        // reduction
        %4 = transform.structured.fuse_into_containing_op %rest_3 into %forall_op_4
        // fill
        %5 = transform.structured.fuse_into_containing_op %2 into %forall_op_4
        // leading
        %6 = transform.structured.fuse_into_containing_op %3 into %forall_op_4
        // fill
        %7 = transform.structured.scalarize %5
        // leading
        %8 = transform.structured.scalarize %6
        // trailing
        %9 = transform.structured.scalarize %tiled_op_5
        // reduction
        %10 = transform.structured.scalarize %4
        // reduction, trailing
        %first_6, %rest_7 = transform.iree.take_first %10, %9 : (!pdl.operation, !pdl.operation) -> (!pdl.operation, !pdl.operation)
        // reduction, reduction
        %first_8, %second = transform.structured.split %first_6 after 8  {dimension = 1 : i64} : !pdl.operation
        // reduction, loops
        %tiled_linalg_op, %loops = transform.structured.tile %first_8[0, 4] : (!pdl.operation) -> (!pdl.operation, !transform.any_op)
        transform.iree.apply_patterns %arg0 {canonicalization, cse, licm, tiling_canonicalization} : (!pdl.operation) -> ()
        // trailing AGAIN
        %forall_op_9, %tiled_op_10 = transform.structured.tile_to_forall_op %rest_7   num_threads [0, 128] tile_sizes [](mapping = [#gpu.thread<x>])
```

This is clearly a bug.

I do not know  the intention of this strategy, the correct fix depends on it:

1. the trailing operation is *not* fused with the reduction, then the leading part of the transform sequence must be  tiling&mapping the reduction operation instead of the trailing operation (when present);
2. the trailing operation *is* fused with the reduction, then, ironically, just deleting the trailing call to tile&map the trailing operation as suggested above would work (so would mapping to other thread_ids if present).

Separately from that, it should be possible to write a dataflow analysis on the transform sequence that could indicate that the same operation is mapped twice to the same thread id, and warn the user.

**Comment by Young768** [comment]
The [IR](https://gist.github.com/Young768/592db9f3c47e62eba5b233bbc827e97c) here, fail.mlir and pass.mlir both have the IR before the ```iree-transform-dialect-interpreter```. See ```// -----// IR Dump Before TransformDialectInterpreter (iree-transform-dialect-interpreter) //----- //``` or are you looking for sth else?
@ftynse  Two things confuse me:
1,  The only fusion is introduced [here](https://github.com/openxla/iree/blob/93781b36026b297bc6c42720a06ffcf55574568a/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.cpp#L104-L114), in which the size of ```opsToFuseH```. Then the leading part and trailing part has empty ```opsToFuseH```.
2, looks like the [reduction part ](https://github.com/openxla/iree/blob/93781b36026b297bc6c42720a06ffcf55574568a/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.cpp#L132-L152) use 1 thread, but the trailing part use 128 thread. Note that both of them has rank=2.
Do you know the intention of doing these?

**Comment by ftynse** [comment]
> The [IR](https://gist.github.com/Young768/592db9f3c47e62eba5b233bbc827e97c) here, fail.mlir and pass.mlir both have the IR before the iree-transform-dialect-interpreter. See // -----// IR Dump Before TransformDialectInterpreter (iree-transform-dialect-interpreter) //----- // or are you looking for sth else?

Yes, that, thank you! Haven't noticed before.

> 1, The only fusion is introduced [here](https://github.com/openxla/iree/blob/93781b36026b297bc6c42720a06ffcf55574568a/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.cpp#L104-L114), in which the size of opsToFuseH. Then the leading part and trailing part has empty opsToFuseH.

That's not exactly right. The three lines below construct more fusion ops. 
https://github.com/openxla/iree/blob/93781b36026b297bc6c42720a06ffcf55574568a/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.cpp#L115-L117.

It's better to look at the transform script, it reflects which transformations are actually applied vs just constructed in a convoluted C++ code.

> 2, looks like the [reduction part ](https://github.com/openxla/iree/blob/93781b36026b297bc6c42720a06ffcf55574568a/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.cpp#L132-L152)use 1 thread, but the trailing part use 128 thread. Note that both of them has rank=2.
Do you know the intention of doing these?

Again, I have two possible explanations:
A. The intention was to map up to 2 parallel dimensions of the reduction and 2 parallel dimensions of the trailing *except for* the most minor one to `threadIdx.{y,z}`, then map the reduction dimension to `threadIdx.x==0` and the most minor dimension of the trailing to `threadIdx.x`.
B. The intention was to map the reduction dimension to `threadIdx.x` (and parallel dimensions to other threads if available), then map to most minor dimension of the trailing to `threadIdx.x`, and have a synchronization between them.

**Comment by ftynse** [comment]
Under the second hypothesis, the issue is then with

https://github.com/openxla/iree/blob/93781b36026b297bc6c42720a06ffcf55574568a/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.cpp#L113-L114

that should be using ~`take_back` instead of `take_front`~ `drop_front(1).take_front(...)`.

**Comment by Young768** [comment]
Both ```take_back``` or ```drop_front(1).take_front``` introduce the overprovisioning issue:

```Trying to map to fewer GPU threads than loop iterations but overprovisioning is not yet supported. Try additional tiling of the before mapping or map to more threads.```

**Comment by ftynse** [comment]
Hmm, it looks like the block size is hardcoded to always be 1 along y and z, which could explain this error. Try doing `strategy.workgroupTileSizes.drop_back()` in  https://github.com/openxla/iree/blob/93781b36026b297bc6c42720a06ffcf55574568a/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.cpp#L111.

This is a rather strange choice performance-wise as reduction will be completely sequential, but it seems consistent with the comment above the `SmallReductionStrategy` class suggesting that reductions are computed sequentially (though "in each thread" suggests that outer dimensions should be mapped to threads, but this needs to be reflected in block mapping and size computation.

It would be preferable to wait for @nicolasvasilache to get back next Monday. He should know what he intended and should be able to propose a fix now that we identified the issue.

**Comment by nicolasvasilache** [comment]
> @nicolasvasilache I think the problem is the trailing part, not the reduction part.
> Either commenting out these [lines](https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Codegen/TransformDialectStrategies/GPU/SmallReductionStrategy.cpp#L143-L152),
> or applying the patch to the trailing part:

Ok but this is in contradiction with the previous information that seems to mention only the reduction op.

> Yes, thats absolute error. I checked it is static op. @jpienaar
> 
> @nicolasvasilache The op is `linalg.generic` with size of 2 operandTypes(), `tensor<128x10xf32>` `tensor<128xf32>` do you need more info?

Thanks for posting https://gist.github.com/Young768/592db9f3c47e62eba5b233bbc827e97c, I can repro from this.



Thanks for diagnosing @ftynse, the trailing part is indeed incorrectly mapped twice, looking.

**Comment by nicolasvasilache** [comment]
Didn't mean to close prematurely, I'd love to see a confirmation that this was indeed the problem.
@Young768 could you please rerun with IREE ToT ?

Thanks much!

**Comment by nicolasvasilache** [comment]
Separately, I was not able to add @Young768 as a reviewer to #13517 which could have been useful.
@GMNGeoffrey is there some configuration change that would be appropriate here ?

**Comment by GMNGeoffrey** [comment]
Looks like they have been added to iree-triage if they weren't already. That should be what is required to add them as a reviewer on an IREE PR

**Comment by Young768** [comment]
@nicolasvasilache thanks. I verified that [PR](https://github.com/openxla/iree/pull/13517) fixed the issue. Closing the issue.

For testing, I was able to add myself as the reviewer.

Thanks all!
