### ISSUE TITLE
Re-enable TF 'tan' integration tests

### ISSUE THREAD

**Issue by dcaballe** [openxla/iree#12011]
Integrate https://github.com/iree-org/iree/pull/11959 had to disable the following tf tests:

```
        iree_tf_tests/math/llvmcpu__complex_dynamic_dim_tan.run
        iree_tf_tests/math/llvmcpu__complex_tan.run
        iree_tf_tests/math/llvmcpu__dynamic_dim_tan.run
        iree_tf_tests/math/llvmcpu__tan.run
        iree_tf_tests/math/vulkan__complex_dynamic_dim_tan.run
        iree_tf_tests/math/vulkan__complex_tan.run
        iree_tf_tests/math/vulkan__dynamic_dim_tan.run
        iree_tf_tests/math/vulkan__tan.run
```
Diagnostics: /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py:746:0: error: failed to legalize operation 'math.tan' that was explicitly marked illegal

**Comment by ScottTodd** [comment]
Those tests were deleted in https://github.com/openxla/iree/commit/1034e40cf4d9f6e1f4c73c2ab0b5eb2ff0cf7e0d. Might be worth adding back at some point using TF Python or StableHLO MLIR.
