### ISSUE TITLE
Can't use ASan on Android/ARM64

### ISSUE THREAD

**Issue by bjacob** [openxla/iree#12014]
At the moment, with `IREE_ENABLE_ASAN=ON`, many tests are failing with `Illegal instruction`, on Android/ARM64.

Unlike TSan where we are specifically building modules with TSAN instrumentation, with ASAN we have been working under the assumption that  it was fine to run non-ASAN-instrumented module code with TSAN-instrumented IREE runtime. Maybe that's not the case anymore ? EDIT: Nope, I tried, it's not the same issue as TSan, and the equivalent fix here (compiling modules with `--iree-llvm-sanitize=address --iree-llvm-link-embedded=false`) does not make a difference.

**Comment by bjacob** [comment]
We are running into exactly this general issue: https://github.com/google/sanitizers/issues/1469

Verified - we are hitting `Illegal instruction` in this `pthread_create` call: https://github.com/iree-org/iree/blob/b7cfaee1e738b151bfe990d06ee89033a9c47329/runtime/src/iree/base/internal/threading_pthreads.c#L180

**Comment by benvanik** [comment]
> Apparently ASAN doesn't support pthread on arm64 (only arm32).

Ouch :|

**Comment by bjacob** [comment]
I'd guess that the downsides of shipping a new version of Android without ASan support outweighs the benefits, but what do I know.

**Comment by allieculp** [comment]
@bjacob Marking as P2, but please adjust priority and status if needed.

**Comment by bjacob** [comment]
We can close this for now. Android/arm64 is in the midst of a transition from ASan to HWAsan. HWASan currently requires a Pixel device with a special OS image flashed on it, so that's quite a high barrier to entry. Android team is working on reducing this friction. If someone wants to act here, 2 courses of action that could deserve their own new Issue (describing for future reference):
* The old ASan path is unsupported but may still be made to work with some half-documented tips. Figure that out and document. Maybe automate what can be automated in our CMake build.
* Track HWASan status, play with it, document and/or enable in CMake build as appropriate. (Technically should be orthogonal to build, unlike old ASan, but I don't know what we'll run into).
