### ISSUE TITLE
PyTorch getting started docs use unstable pip commands

### ISSUE THREAD

**Issue by ScottTodd** [openxla/iree#12034]
https://iree-org.github.io/iree/getting-started/pytorch/

The stable `iree-compiler` and `iree-runtime` packages are currently quite outdated, so users are reporting version skew issues ([discussion on Discord](https://discord.com/channels/689900678990135345/689900680009482386/1070426048119980103))

The install steps can probably be replaced with just `pip install git+https://github.com/iree-org/iree-torch.git`, which then looks at https://github.com/iree-org/iree-torch/blob/main/requirements.txt (which sets `-f https://iree-org.github.io/iree/pip-release-links.html` to install from nightly IREE releases instead of just the stable releases published to pypi). Eventually we need these pip install commands to be more stable across tool and framework versions.

We can also add some notes about installing packages directly if needed.

**Comment by ScottTodd** [comment]
Well, just `!pip install git+https://github.com/iree-org/iree-torch.git` fails in Colab after 12 minutes:

```py
!pip install git+https://github.com/iree-org/iree-torch.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/iree-org/iree-torch.git
  Cloning https://github.com/iree-org/iree-torch.git to /tmp/pip-req-build-wx2w6tbh
  Running command git clone --filter=blob:none --quiet https://github.com/iree-org/iree-torch.git /tmp/pip-req-build-wx2w6tbh
  Resolved https://github.com/iree-org/iree-torch.git to commit f84123ddb1086cc32674883114672e78c379a545
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Collecting iree-compiler
  Downloading iree_compiler-20220930.282-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (49.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 MB 7.7 MB/s eta 0:00:00
Collecting iree-runtime
  Downloading iree_runtime-20220930.282-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 10.3 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement torch-mlir (from iree-torch) (from versions: none)
ERROR: No matching distribution found for torch-mlir
```

These repos and docs need some attention from someone more familiar with them. @dellis23 maybe?

**Comment by dellis23** [comment]
Thanks for the heads up.  We've recently put an [inactivity notice](https://github.com/iree-org/iree-torch/commit/7c1b597081e2a7baf39e719da2de01bbd6ad1570) on iree-torch, as we aren't going to be able to really maintain it going forward, and it isn't in a very stable state right now.  I forgot we need to change these docs too.  Unfortunately it seems like the best course of action is to probably remove the documentation from the main IREE getting started pages.  I can do that.

**Comment by ScottTodd** [comment]
iree-torch use is obsolete now. Planning more PyTorch doc updates that shouldn't have this issue.
