### ISSUE TITLE
Bufferization is particularly slow for large programs

### ISSUE THREAD

**Issue by ScottTodd** [openxla/iree#12035]
Part of https://github.com/iree-org/iree/issues/11994

When tracing the compiler, the `EliminateEmptyTensors` pass and `IREEComprehensiveBufferize` pass (sources in [IREEComprehensiveBufferizePass.cpp](https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/Common/IREEComprehensiveBufferizePass.cpp)) shows up as taking a long time when compiling programs like the one linked at https://github.com/iree-org/iree/issues/11994#issuecomment-1409231149 (at least for Vulkan):

![image](https://user-images.githubusercontent.com/4010439/216189941-652d3bd8-18ef-4f50-b344-47d130fe9d58.png)

![image](https://user-images.githubusercontent.com/4010439/216190025-3cece0eb-2def-4b6a-9412-221b31ec0b69.png)

Note from the trace (Debug mode, but probably applicable to Release) that
* executable translation is running in parallel, so this isn't necessarily a bottleneck
* the timing distribution has a few spikes (60ms, 5 seconds) and several outliers (1m40s)

It would be nice to include function names or locations in compiler traces for easier correlation between trace zones and IR dumps. I could guess at which executables are slow based on data sizes or the number of ops...

---

We also discussed this a bit [here on Discord](https://discord.com/channels/689900678990135345/689900680009482386/1069737477528633465). @MaheshRavishankar @benvanik

**Comment by benvanik** [comment]
> executable translation is running in parallel, so this isn't necessarily a bottleneck

It is a bottleneck - we could shave 3mins off the total compile time by fixing those (3.5min -> .5min) - when parallel the longest single task is what defines latency and these are wayyy too long :)

There's also throughput: that indicates that 32 minutes of CPU time is spent in those two passes - that's _a lot_ of compute that can't be done because it's spent there. Another way to think about it is that if it takes 32mins on 32 cores if you made it take 16mins it's like getting 32 more cores in your system for free!

For perspective, I use about the same amount of CPU time compiling iree-compile: compiling a handful of small shaders should not take as long as compiling all of LLVM/MLIR/IREE :)

**Comment by MaheshRavishankar** [comment]
FYI @matthias-springer

**Comment by matthias-springer** [comment]
We should be able to get a ~50% speedup by reusing the bufferization analysis in `EliminateEmptyTensors` and `IREEComprehensiveBufferize`. Both run the bufferization analysis.

There are probably additional opportunities to improve inside the analysis by caching various IR traversals etc.

**Comment by ScottTodd** [comment]
Here's one of executables that is slow to bufferize (`--iree-hal-target-backends=vulkan --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs -iree-vulkan-target-triple=rdna3-unknown-unknown`)

https://gist.github.com/ScottTodd/9c6d0bc780762634c907df3666852f59

![image](https://user-images.githubusercontent.com/4010439/216415647-bca974ca-cf2d-40ad-b86e-db12b392d485.png)

**Comment by matthias-springer** [comment]
Am I reading the chart right, is a single compilation running for 28 seconds? That would be way too slow... How large is the input (let's say in input file kilobytes)? We haven't looked into performance of the bufferization framework much. I think there are many low-hanging fruits.

**Comment by benvanik** [comment]
Correct - that single compilation of https://gist.github.com/ScottTodd/9c6d0bc780762634c907df3666852f59 takes 28sec :)

**Comment by ScottTodd** [comment]
I'll see if I can get Tracy sampling working for at least that part of the compilation. A function by function breakdown of the time spent would be really useful.

**Comment by ScottTodd** [comment]
I got sampling working (needed `-DIREE_LINK_COMPILER_SHARED_LIBRARY=OFF` on Windows - I'll enforce that via CMake and check what else Linux needs). Here's one screenshot of what bufferization is doing for the program / config I've been looking at:

![image](https://user-images.githubusercontent.com/4010439/216736696-2ba107c8-3491-40d9-86f0-8fe5e1cff077.png)

**Comment by ScottTodd** [comment]
I can poke more at the trace next week (and share it / help with a walkthrough), but here's another screenshot: 
![image](https://user-images.githubusercontent.com/4010439/216737040-d56d73a2-7d86-45d6-94e2-6255733c0f9d.png)

**Comment by matthias-springer** [comment]
How can I reproduce this? Can you share an `iree-compile`/`iree-opt` command line and .mlir file that I can run?

**Comment by ScottTodd** [comment]
As for running Tracy on the compiler, this works on Windows:

* Patch https://github.com/iree-org/iree/pull/12043 for more detailed information in traces
* Build `iree-compile` with these CMake options:
`-DIREE_ENABLE_RUNTIME_TRACING=ON -DIREE_ENABLE_COMPILER_TRACING=ON -DIREE_LINK_COMPILER_SHARED_LIBRARY=OFF`
* Run `iree-compile` as admin for sampling, or regular user for just instrumentation

(I'll make sure our docs are up to date and demo that workflow a bit soon)

**Comment by benvanik** [comment]
the standalone hal.executable can also be passed to iree-compile on its own with --compile-mode=hal-executable, or iree-opt with --iree-hal-transformation-pipeline (IIRC, have to check, it's been awhile)

**Comment by ScottTodd** [comment]
Looks like a few improvements to bufferization performance have landed and been integrated into IREE.

For that `unet2base_8dec_fp16_torch` program, I see that total time in `IREEComprehensiveBufferize` dropped from 5m20s to 2m55s (current on the left, 2 months ago on the right): 
![image](https://user-images.githubusercontent.com/4010439/229600185-5082c026-8d19-4e2b-9e49-639300b6d0e8.png)

However, in that particular program's compilation, there are still a few severe outliers that actually got worse? Here's some IR for `forward_dispatch_182`, which is mostly doing `%8 = iree_linalg_ext.softmax dimension(2) ins(%6 : tensor<20x1024x77xf16>) outs(%7 : tensor<20x1024x77xf16>) -> tensor<20x1024x77xf16>`: https://gist.github.com/ScottTodd/43d4c8e275f7597984492fc38b2d0c1c (yes, that's 12349 ops in spirv module...)

This might just be a sign that codegen prior to bufferization is doing something silly (that IR certainly looks silly to me :P)

**Comment by MaheshRavishankar** [comment]
@antiagainst seems like the vector size computation is broken

**Comment by antiagainst** [comment]
Yeah. 77 as the innermost dimension size would trigger unrolling to 1. Right now tiling pretty much only tries some power of two. Would need to adjust tiling a bit to materialize a loop for these odd numbers. I'll look into handling this a bit later..

**Comment by antiagainst** [comment]
> Yeah. 77 as the innermost dimension size would trigger unrolling to 1. Right now tiling pretty much only tries some power of two. Would need to adjust tiling a bit to materialize a loop for these odd numbers. I'll look into handling this a bit later..

https://github.com/openxla/iree/pull/12922 to improve the situation here.

**Comment by ScottTodd** [comment]
Nice! With those improvements to tiling/unrolling, compile time for bufferization on vulkan/spir-v is in a much better place.

Here's the same unet program from my previous comment now:
![image](https://user-images.githubusercontent.com/4010439/230435777-f5cbbf7d-5ddc-4d07-8db3-91647c48885a.png)

`IREEComprehensiveBufferize` now has no large outliers and takes 21s total (73ms mean over 295 instances). Time spent in the `HAL` phase of lowering dropped from ~1m30s to just ~30s.

Here's the dispatch IR after: https://gist.github.com/ScottTodd/d99135127845affccd94caf031094ade (12000+ ops -> ~1000 ops, nice order of magnitude reduction but still rather large)

I'm comfortable calling this issue (focusing on `EliminateEmptyTensors` and `IREEComprehensiveBufferize`) fixed, though we should keep an eye on unrolling and code bloat behavior across all of our backends, since many of the passes we depend on take time proportional to the number of ops in the module.

**Comment by antiagainst** [comment]
Awesome! Thanks Scott for driving this! :D
