### ISSUE TITLE
Move IREE Repository to OpenXLA GitHub Organization

### ISSUE THREAD

**Issue by GMNGeoffrey** [openxla/iree#12102]
# IREE -> OpenXLA

As [announced](https://groups.google.com/g/iree-discuss/c/nyKwVGXJf6U), this
repository https://github.com/iree-org/iree is moving to the OpenXLA GitHub
organization as https://github.com/openxla/iree

## Moving a GitHub Repository

GitHub has
[built-in tooling](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository)
for moving a GitHub repository from one organization to another. This includes
transferring all issues, PRs, wikis, and various metadata. It will also forward
the old links, so users could still clone from `iree-org/iree` for instance and
it will
[seamlessly forward them to the new location](https://github.blog/2013-05-16-repository-redirects-are-here/).
The same is true of GitHub API requests. The redirect remains in place
indefinitely unless there exists another repo at the old location. So we should
have no worries about forwarding as long as we don't create `iree-org/iree` as a
new repository in the future. I'm not aware of a way to create an explicit
tombstone repository as creating a repository with the old name breaks the
automatic url forwarding. One notable exception to the redirection is for
`github.io pages`, which are not forwarded (see
[Docs Forwarding](#docs-forwarding)).

## Issues

When we migrated IREE into the `iree-org` GitHub organization, a number of things
went somewhat wrong, but fortunately we wrote those down. We'd like to avoid a
repeat of those issues where possible.

### Kokoro

We had a bunch of issues last time with Kokoro. Fortunately, we no longer use
Kokoro, so this will not be a problem 🙂

### GitHub Projects

We use
[GitHub Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects)
for tracking and triaging issues. We have a single
[project](https://github.com/orgs/iree-org/projects/1) that contains all the
issues. Projects exist at the organization level and can contain issues from
multiple repositories, but only within the same organization. So if we migrate
only the IREE repo then the Project will not be able to contain issues from the
other repositories. Fortunately, only one open issue in the Project is from a
repo other than the main IREE repo, so this shouldn't be too big of a problem.
GitHub does not provide tooling for importing, exporting, or migrating Projects
(https://github.com/orgs/community/discussions/12908). Last time I created a
bespoke
[script](https://gist.github.com/GMNGeoffrey/1768f49339655d2a8ef5f152ab64b0d4)
to do most of the migration. At the time there was no API access to Project
Views, but those are now present in the schema. Additionally, it now provides
functionality to copy the views and custom fields of a project to a new project
in a different organization, so we should be able to do that and then populate
the issues with the scripting. Unfortunately this isn't something we can do
ahead of time, so there will necessarily be downtime for the Project, but we can
thoroughly test migration scripting ahead of time.

### Tokens

There are a variety of tokens we use in various automation. We will need to do a
thorough audit of these and make sure they are all updated. Most of these are
owned by the `iree-github-actions-bot` account, so we should add that bot to the
OpenXLA organization ahead of time. Ideally we would make the existing tokens
also have OpenXLA permissions so that we don't have to hot-swap the tokens after
the repo is moved. We store tokens in GitHub actions secrets and GCP Secret
Manager.

GitHub's new
[fine-grained tokens](https://docs.github.com/en/organizations/managing-programmatic-access-to-your-organization/setting-a-personal-access-token-policy-for-your-organization)
only allow access to a single organization per token. These will require either
hot-swapping the tokens on the day of migration, or reverting back to the
broader access tokens with access to both old and new repo locations. To limit
the number of things that need to be done during the migration, I recommend the
latter. This is an inventory of all the GitHub tokens in use today. Note that
links to the GitHub tokens page must be opened while logged in to GitHub as
`iree-github-actions-bot` (IREE team members can open in incognito and then log
in as the bot). GitHub Secrets access will require admin privileges on the IREE
repository. Secret Manager metadata access will require the GCP "Secret Manager
Viewer" role.

- GitHub token for Buildkite: GitHub `iree-github-actions-bot` classic personal
  access token used by the Buildkite benchmark pipeline
  - [GitHub Token Page](https://github.com/settings/tokens/1044390657)
  - [VM Holding the token on disk](https://console.cloud.google.com/compute/instancesDetail/zones/us-central1-a/instances/buildkite-report?project=iree-oss)
  - [Code usage](https://cs.github.com/iree-org/iree?q=GITHUB_TOKEN+path%3Abuildkite)
  * Required action: None. Access is only for public repos and gists. But also
    we should just delete this whole pipeline...
- GitHub token for posting gists: GitHub `iree-github-actions-bot` fine-grained
  personal access token used by new benchmark workflows to create a detailed
  results table that can be linked to.
  - [GitHub Token Page](https://github.com/settings/personal-access-tokens/628564)
  - [GitHub Secret](https://github.com/iree-org/iree//settings/secrets/actions/GIST_BOT_TOKEN)
  - [Code Usage](https://cs.github.com/iree-org/iree?q=GIST_BOT_TOKEN)
  * Required action: None. This is scoped at the user level and is only for
    gists.
- GitHub token for adding to Project: GitHub `iree-github-actions-bot` classic
  personal access token used by the workflow that adds new issues to the IREE
  GitHub project
  - [GitHub Token Page](https://github.com/settings/tokens/884290188)
  - [GitHub Secret](https://github.com/iree-org/iree//settings/secrets/actions/ADD_TO_PROJECT_TOKEN)
  - [Code Usage](https://github.com/iree-org/iree//blob/ddd05c9f42/.github/workflows/process_opened_issues.yml#L17)
  * Required action: `iree-github-actions-bot` must be a member of the openxla
    GitHub organization
- GitHub token for write access to repositories: GitHub iree-github-actions-bot
  fine-grained personal access token used in various GitHub actions workflows
  to update the contents of the IREE repository.
  - [GitHub Token Page](https://github.com/settings/tokens/1090084493)
  - [GitHub Secret](https://github.com/iree-org/iree//settings/secrets/actions/WRITE_ACCESS_TOKEN)
  - [Code Usage](https://cs.github.com/iree-org/iree?q=WRITE_ACCESS_TOKEN)
  * Required action: We must revert this back to a classic token. We need to
    create a new classic PAT with the correct permissions and update the GitHub
    secret to use that instead. Rollback procedure is to update the secret value
    back to the old value. `iree-github-actions-bot` needs to have write access
    to the IREE repository in the new location.
- GitHub app for runner registration: GitHub app installed in `iree-org` that
  allows administering organization runners via a proxy service.
  - [App installation](https://github.com/organizations/iree-org/settings/installations/27365050)
  - [Secret manager entry](https://console.cloud.google.com/security/secret-manager/secret/github-token-proxy-app-private-key/versions?project=iree-oss)
  - [Code usage (different repo)](https://github.com/google-github-actions/github-runner-token-proxy)
  * Required action: GitHub app must be installed in `openxla` org
- Discord Webhook: URL for webhook so that workflows can post to the IREE
  discord
  - [GitHub Secret](https://github.com/organizations/iree-org/settings/secrets/actions/DISCORD_WEBHOOK)
  * Required action: Secret must be duplicated to the OpenXLA organization

### Hardcoded Organization Name

In a few places, we have the `iree-org` name hardcoded in a script or something.
This is especially the case in some GitHub Actions workflows where we have
historically disabled jobs when not running in our repository such that we don't
spam people's forks. There are now other mechanisms for people to disable all or
individual actions in their forks, so I question the value of these
short-circuits. In cases where we do need to keep them, we can `and` with the
openxla org name ahead of the migration.

### Human Access

In our previous org migration, human permissions for repositories ended up in a
very strange state and we didn't have any way to see what it had been after the
repo got migrated. We should dump the pre-migrations state so that we can
reference it. As much as possible, we should set up permissions to the new
organization ahead of the repo move so that they can be validated and there's no
downtime.

The OpenXLA organization has much more organized permissions setup than
iree-org. Our permissions grew somewhat organically, partially because we didn't
have our own GitHub organization originally, so were more limited in our
options. We can incorporate IREE core team members and external collaborators
into the OpenXLA organization groups ahead of the migration.

OpenXLA has all permissions assigned at the org level rather than the repo
level. Even in cases where a person or group has access only to specific repos,
that access is still set at the org level. That is, there are groups at the org
level that are granted admin access, write access, etc to specific repositories.
This is useful for being able to easily view and edit the configuration in one
place. One limitation is that only members of the organization can be in this
team, so giving someone access to a repository requires adding them to the
organization. We have decided that having those coupled is ok. We can configure
settings so that being an organization member does not give any privileges (e.g.
creating new repositories) beyond those explicitly granted.

In IREE we make some external contributors collaborators, which allows them to
do things like run CI without approval, add labels to issues, request PR
reviews, etc. Currently repo admins of individual repos can add these external
collaborators, so they can take action without having to escalate to admins. To
enable this workflow, we will make some team members maintainers of specific
teams and they can add users to those teams. This will also allow them to
quickly remove bad actors if necessary. Adding people directly to repositories
will be discouraged and adding outside collaborators will be disabled entirely.

### Colab Notebooks

After our previous migration, Colab notebooks viewed at their new URLs were
listed as "untrusted" ("not authored by Google"). We need to get on the list for
being a "trusted" repository (internal process).

### Docs Forwarding <a name="docs-forwarding"></a>

GitHub's automatic URL forwarding does not extend to github.io pages. Since our
last migration, old links to https://google.github.io/iree have 404ed and the
Google index continued to find these resources instead of the new ones for
weeks. It's unclear to me why GitHub doesn't set up this forwarding
automatically, but a user has documented a
[simple process](https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7)
for doing so, as it is possible to claim the root `<org>.github.io` site and
then set up the appropriate redirects. A
[similar mechanism](https://github.com/google/google.github.io/blob/def9300f19/404.html#L98)
is already in place for some repos in google.github.io.

### Communication

Last time communication was fragmented across many different internal and
external channels. For this migration we should document clear locations for
where the following discussion should take place:

1. Public announcements about the plan for the migration and high-level status
   updates or actions required. We will use a single thread on the iree-discuss
   mailing list.
2. Detailed updates about the migration progress and task tracking. This GitHub
   issue in the IREE repository.
3. Realtime reports of issues. This will be especially relevant for post-move
   issues (e.g. "I can't access the repo"). We will encourage posting on the
   GitHub issue, but also have a pinned thread in the IREE discord #general
   channel. This will only be created when the migration proper begins. No
   updates or announcements of broad interest should only be communicated here.
   Discord should be treated as ephemeral. The first post in the thread will
   direct people to the GitHub issue.
4. Internal-only realtime conversations. I can't think of a reason for these to
   exist, but it's good to be prepared. We will encourage no internal-only
   discussion, but create a thread in the dev chat room. The first post in the
   thread will direct people to the GitHub issue.

As much communication as possible should happen on the GitHub issue. It is
almost inevitable that someone will post about this in Discord, so a dedicated
thread might be helpful in consolidating that conversation. Internal-only
communication should be rare, but might happen, and we should therefore
establish communication channels ahead of time. The mailing list thread should
be reserved for announcements from those actively conducting the migration that
require broad dissemination either because users need to take action or because
they are broadly relevant high-level planning and progress updates.

### GitHub Runners

One migration problem we face today that we didn't the last time is our use of
custom GitHub runners. Those custom runners managed by GitHub can be created
ahead of time in the new organization without issue (they autoscale nicely). Our
self-hosted runners are run on GCE Managed Instance Groups (MIGs) and have a lot
more issues with autoscaling. They are also more resource constrained as we
not-infrequently hit cloud quota limits. These are likely going to be the most
work to migrate. There's going to be some auth and tokens that will need to be
extended. We're also going to need to duplicate all the runner managed instance
groups because a runner can only target a single organization. That may cause us
some quota issues although we'll luckily only have real traffic on one repo at a
time. I think we should be able to handle it within the current IREE cloud
project quota without too much disruption, but we should probably investigate
whether we can easily get additional quota (especially CPU).

We also use GitHub managed runners, both the standard ones, where we make use of
increased minutes from Google's GitHub Enterprise plan and larger custom managed
runners. Full use of runner features requires an enterprise plan. `iree-org` is
currently linked to Google's enterprise account, but `openxla` is not. We'll
need to add it.

### Buildkite

We still use Buildkite for some of our benchmarking (migration to GitHub actions
in progress). Here the runners ("agents" in Buildkite terminology) are connected
to the repository. Our custom actions use a PAT for `iree-github-actions-bot`,
but Buildkite uses its own integration to gain access to things like publishing
commit statuses. We can install the Buildkite app in the new organization, but
it may be necessary to manually reconfigure each pipeline to point at the new
repository location. Even though GitHub would forward a request, the
installation will be different between the orgs and Buildkite might use the
wrong credentials. We can do some testing using the new repository location, but
won't be able to precisely mimic the setup. The pipelines may be temporarily
broken and we'll need to manually update each pipeline after the migration.

### Ahead of Time Testing

Ideally we'd test that the new repository was working before we switched off the
old one. There isn't any way to do this with GitHub tooling though, AFAIK. You
can only move a repository, not gradually redirect traffic with dual writes
:stuck_out_tongue:. We can fork (has to be a fork for PRs to work)
the repository and test almost everything there first. GitHub
doesn't let you move a repo to an org if it already has a repo of that name.
That seems reasonable in general, but is a bit annoying here. We'll need to
delete the copy before migrating the new repo, which might invalidate some
configuration. Any configuration done with the forked repo itself will be lost,
which may include things like organization runners that have been configured to
be accessible for that repo. There will necessarily be some amount of winging it
and hotfixes on the day of migration. This will need to happen at a time when
the relevant people are around.

# Detailed Steps

## Ahead of time testing

- [x] Create a GitHub issue in the IREE repository for work tracking
- [x] Communicate the intent to move the repository and details of the steps
      involved on iree-discuss
- [x] Add the OpenXLA GitHub organization to Google's enterprise account
- [x] Update all hardcoded organization names in code to also work with the new
      organization. Consider removing some organization hardcoding entirely.
      #12012
- [x] Create a new `iree-github-actions-bot` WRITE_ACCESS_TOKEN as a classic PAT
      and update the value in the repository secrets.
- [x] Create a fork of the IREE repository in the OpenXLA GitHub organization
    - [x] Add a note in the description that this is scaffolding for a
          migration, not the main repo.
    - [x] Limit interactions to collaborators to avoid accidental PRs/issues
- [x] Create GitHub teams for IREE admin/write/triage with appropriate access to
      the repo copy.
- [x] Create an IREE GitHub team in the OpenXLA GitHub organization and add it
      to the team for write access
- [x] Dump all current access to the IREE repository from the API
- [x] Add `iree-github-actions-bot` to the IREE write access team
- [x] Duplicate GitHub self-hosted runner setup in new org:
    - [x] Increase GCP quota
    - [x] Install GitHub runner proxy app in `openxla` organization.
          https://github.com/organizations/openxla/settings/installations/33754927
    - [x] Duplicate Cloud Run
          [proxy service](https://console.cloud.google.com/run/detail/us-east1/ght-proxy?project=iree-oss)
          to operate on new org (requires different installation id
    - [x] Make
          [instance-self-deleter service](https://console.cloud.google.com/run/detail/us-central1/instance-self-deleter?project=iree-oss)
          work with new MIG names
    - [x] Script the creation of new MIGs
    - [x] Duplicate all runner MIGs with disambiguating names
    - [x] Make runners accessible to fork repository
    - [x] Test PR submission with presubmit and post-submit testing
- [x] Test Buildkite pipelines
    - [x] Duplicate one of the benchmark Buildkite pipelines and set it up pointing
      at the copy repository
    - [x] Install Buildkite app in `openxla` org with access to the `iree` repo. https://github.com/organizations/openxla/settings/installations/34003870
    - [x] Ensure that it is able to receive webhook events and post commit
          statuses
    - [x] Create a test repository in iree-org, configure Buildkite to work with
          it (test that this functions), then move it to the `openxla` org and see
          if Buildkite falls over.
- [x] Create a team for IREE collaborators and add it to the IREE triage team
- [x] Invite all current repo external collaborators to the collaborators team
- [x] Validate that an IREE team member can take expected actions in the repo copy:
    - [x] Create PR
    - [x] Access GitHub actions logs
    - [x] Rerun GitHub actions
    - [x] Merge PR
- [x] Validate that a collaborator can take the same expected actions
- [x] Add openxla/iree to trusted repos for Colab
- [x] Validate that Colab notebooks appear as trusted
- [x] Create github.com/iree-org/iree-org.github.io to auto-forward docs pages
- [x] Validate docs forwarding using a different address (to avoid conflict
      before the move)
- [x] Revert all GitHub tokens to non fine-grained access and extend them to the
      OpenXLA organization as well.
- [x] Discord Integration
    - [x] Copy DISCORD_WEBHOOK secret to `openxla` organization
    - [x] Test that posting to Discord works
- [x] Test GitHub Project migration
    - [x] Create a test-repository in `iree-org`
    - [x] Create a test org-level project in `iree-org`
    - [x] Create a test org-level project in `openxla`
    - [x] Populate the test-repository with test issues
    - [x] Add the test issues to the project in `iree-org` and add project metadata
    - [x] Move the test-repository from `iree-org` to `openxla`
    - [x] Adapt previous script to add all issues to the project in `openxla` (iterate)
    - [x] Validate project migration
    - [x] Test that automatic addition of new issues works
- [x] Delete fork repository
- [x] Announce precise date and time for moving the IREE repository

## Migration

- [x] Raise autoscaling limits and fixed sizes on openxla org runner groups 
- [x] Disable workflow to automatically add new issues to the GitHub Project
- [x] Dump items from the old IREE GitHub Project (in case things get messed
      up)
- [x] Create a new GitHub Project in openxla for IREE
- [x] Move the IREE repository to `openxla/iree`
    - [x] Add the iree-admin, iree-write, and iree-triage teams to the repository
- [x] Give the repository access to the org-level runner groups
- [x] Turn on docs forwarding with `iree-org.github.io` repository
- [x] Run project migration to copy the old GitHub project to the new
      organization
- [x] Turn on Project workflows matching old project
- [x] Validate that Buildkite can post commit statuses.
- [x] Scale down iree-org runner groups
- [x] Validate that Colab notebooks appear as trusted
- [x] Replace all old links in the repository (they autoforward, but still
      better to use the canonical location)
- [x] Replace all old links in other locations
- [x] Time passes. Deal with issues as they arise
- [x] Delete old runner MIGs
- [x] Set up docs forwarding for `google.github.io`
- [x] Archive old GitHub Project in `iree-org` (Project, not repo!)

**Comment by GMNGeoffrey** [comment]
Well turns out something has to be a public fork in order to function basically at all, so we'll go with a fork after all

**Comment by GMNGeoffrey** [comment]
And by deleting the copy repository, I have confirmed that this deletes its access to runner groups and teams' access to the repository

**Comment by GMNGeoffrey** [comment]
Scott observed that one thing that won't get auto-updated is email filters :-) I'll include a reminder about that in the migration announcement

**Comment by GMNGeoffrey** [comment]
In trying to test Buildkite, I'm running into weird issues with getting it to clone a new repo over ssh. I've configured the pipeline just like our benchmark pipeline:

![image](https://user-images.githubusercontent.com/5732088/217689671-7c2e8974-2be8-479e-a3e4-820ef3d8ccf7.png)

vs

![image](https://user-images.githubusercontent.com/5732088/217689727-02f16403-5e22-4cbf-9664-0c86f3b56a7a.png)


but [ssh cloning fails](https://buildkite.com/iree/gcmn-test-pipeline/builds/853#018633af-7e1e-4ab0-8f3d-bb75a7d8f479). I've tried the usual "just reset things" options, like sshing into the agent and deleting the Buildkite job directory. It gets weird though. Looking at the logs for the benchmark pipeline, it actually *isn't* cloning over ssh! It's using https even though the pipeline settings say to use ssh.... wtf?

https://buildkite.com/iree/iree-benchmark-linux/builds/2944#01863352-1815-44fc-a28b-24c9c7e60dae

And note this isn't an initial clone vs `remote set-url` thing. https://buildkite.com/iree/gcmn-test-pipeline/builds/851#018633a7-e4f4-4ac3-a070-10e3e1ac3b52 is also using an existing remote, but it sets it to ssh.

@pzread @antiagainst is there some kind of configuration on the Buildkite agents that is sneakily rewriting this as https?

**Comment by GMNGeoffrey** [comment]
Ok I'm totally mystified. I'm going to set both pipelines to https at the pipeline settings level

**Comment by GMNGeoffrey** [comment]
Ok, as I feared, even if Buildkite is installed in both organizations, when you move it from one to another, it stops being able to post commit statuses.

**Comment by GMNGeoffrey** [comment]
Huh, or maybe not. Now it seems to be working. I'll just add a step to validate this is working after the migration

**Comment by GMNGeoffrey** [comment]
I'm now testing project migration. I've copied all the views to the openxla org with https://github.com/orgs/openxla/projects/13. I'm now going copy all IREE issues to the test repo. I want to avoid side-effects though, so I'm going to leave out all assignees, comments, and body text (could have `@` mentions) and just duplicate number, title, and labels

**Comment by GMNGeoffrey** [comment]
Well it turns out the GitHub API really doesn't like it when you try to create 12k issues. I'm following all the [guidelines](https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits), but still hitting the "secondary rate limits" intended to prevent abuse. I've got exponential backoff and such in there as well, so hopefully we'll get them all eventually. So far, I've copied ~2500 issues.

The other fun thing I ran into is that apparently it is possible to end up with gaps in the issue numbering. One source of these is discussions, which apparently share the issue numbering pool, but don't show up in the issues API. At least one issue link says the issue was deleted (ok, I guess that makes sense). The most mysterious is https://github.com/iree-org/iree/issues/1401, which just 404s. Current theory is that the issue was transferred to another repository, but we have no way to confirm this that I can think of. Anyway, I added in placeholders for the missing issues to increment the issue number (that's also what I'm doing for PRs).

**Comment by GMNGeoffrey** [comment]
Alrighty, this isn't going to work. GitHub doesn't publish its secondary rate limits, but I've reverse-engineered the one for issue creation to be 20 per minute and 150 per hour (https://github.com/cli/cli/issues/4801#issuecomment-1430651377). That's even if you issue a single (or batched) request via the GraphQL API. It will create the first 20 issues and then error on the rest: the limit is on modifications, not API requests. With over 12k issues in the IREE repository, that would take 80 hours to copy them all over. That's just not worth it with a goal migration date next week (migration would finish sometime on Saturday. It's not clear whether apps have different secondary rate limits, since those aren't published either :roll_eyes: I can try using an app token and see if it goes any better, but I'm not hopeful. It appears that 0.05 QPS is just too much for the poor GitHub servers. 

I'm amending the plan. I can create a test project in iree-org that has the same views and populate it with some issues from a test repository. Then I'll try migrating the project to a similar test project in `openxla` and validate the process. Then I'll simulate an actual migration: I'll clear out the project, move the test repository to the `openxla` org, and run the migration script.

**Comment by GMNGeoffrey** [comment]
I've confirmed that docs forwarding works. Process:

1. Created `iree-org/test-repository` with a GitHub pages site
2. Added redirect of test-repository to the openxla org to the site for https://github.com/iree-org/iree-org.github.io
3. Confirmed that https://iree-org.github.io/test-repository *did not* redirect and still went to the published site.
4. Moved the repo to `openxla/test-repository`
5. Published a new version of GitHub pages (this is apparently required to get the old site to go away)
6. Confirmed that a redirect from https://iree-org.github.io/test-repository to https://openxla.github.io/test-repository succeeds (as do paths `/test-repository/foo` and `/test-repository/foo/bar`)

I've added a redirect for `iree` ahead of the move. Since this is on the 404 page, this does not interfere with the existing site at iree-org.github.io/iree. Only if GitHub falls back to the main sites page does this get triggered via a 404 that then performs a redirect. I also confirmed that this is treated by search engine indexers in the way we want. An old [test by Search Engine Land](https://searchengineland.com/tested-googlebot-crawls-javascript-heres-learned-220157#:~:text=1.%20JavaScript%20Redirects) determined that javascript modification to `window.location` are treated like an HTTP `301 Moved Permanently` and the index is updated to use the new URL for the site, copying over all ranking signals, etc.

**Comment by GMNGeoffrey** [comment]
The scaled down project migration test worked without a hitch. I've got a dump of the IREE GitHub project to confirm that works. I'll collect a fresh version immediately prior to the migration, in case anything changes between then.

Based on advice from a GitHub engineer on the CLI in https://github.com/cli/cli/issues/4801#issuecomment-1431394355, I reached out to GitHub support to ask about a temporary exception to secondary rate limits so that I could do the full test, but I didn't hear back.

A couple issues with the dump:
1. "draft issues" that exist only in the project are a pain to migrate and my script doesn't handle them. We have two of these and I can copy them over manually if desired, or maybe I'll just make them real issues
2. GitHub apparently doesn't provide any way to get archived items (https://github.com/community/community/discussions/42727). OTOH our attempt to archive old items appears to not have worked even though the GitHub UI lists them as archived, so that is only a couple issues that I archived manually. I don't know how I can find them and unarchive them so they'll get migrated. So a couple of closed issues may fall through the cracks there

**Comment by GMNGeoffrey** [comment]
GitHub support got back to me, pointing me to an issue import API that doesn't send notifications and so isn't subject to the same secondary rate limits. Of course this API is only documented in a [random gist](https://gist.github.com/jonmagic/5282384165e0f86ef105) and hasn't been maintained since 2016. I tested it out and was able to get it to work. It was indeed much faster than the normal create API, but still only averages 4 seconds per issue. That would mean a complete migration of 12k+ issues would take about 13 hours. Given that I was able to do a scaled-down test, I'd prefer to complete the migration at the originally scheduled time rather than postponing so that I can import everything everything with this new API for a full-scale test

**Comment by benvanik** [comment]
(out of the loop, but you're not saying we're doing something that's going to lose our issues, right? repo moves shouldn't need to recreate all the issues?)

**Comment by GMNGeoffrey** [comment]
No we're not going to lose our issues. I was just trying to copy them to a test repo so that I could do a full-scale test of migrating the GitHub project, which we do have to do ourselves (I've got a script we used last time)

**Comment by GMNGeoffrey** [comment]
So I've gotten a dump of our GitHub Project, but it appears that there's no way to list archived issues. I don't think these will be able to come along for the ride. If we figure out a way, we could copy them after the fact, since they shouldn't change or be actively used.

**Comment by GMNGeoffrey** [comment]
Transferring the repository now. First hiccup:

![image](https://user-images.githubusercontent.com/5732088/220479561-abf753f2-f6c7-455c-a771-402dbd0d65b8.png)

> External collaborators have access to this repository, but the openxla organization doesn't allow them. You must remove their access from this repository or enable "Allow repository administrators to invite outside collaborators to repositories for this organization" on the openxla organization before it can be transferred to the openxla organization.

I'm going to temporarily disable that setting so no one loses access and I don't mess things up, but external collaborators should in the future have access through the new organization teams

**Comment by bhack** [comment]
You have crossed the event horizon... :night_with_stars:  this comment is already on the other side. :wink:

**Comment by GMNGeoffrey** [comment]
With https://github.com/openxla/iree/pull/12304 and https://github.com/openxla/iree/pull/12309, all remaining references to iree-org are for repos that haven't been moved yet except for https://github.com/openxla/iree/issues/12318, which I've filed to be handled separately (it's not clear how it should be updated).
