### ISSUE TITLE
Get the ukernel library building to bitcode + objects for use in codegen.

### ISSUE THREAD

**Issue by benvanik** [openxla/iree#12112]
PR #12097 adds the initial support for `iree_bitcode_library`, allowing us to compile C code to bitcode for inclusion in the compiler binary for injection during executable translation. `iree/builtins/device` was ported to use that path but there's a few things needed to get the ukernel library switched over as well.

The end state is that we have a bitcode file per major architectural target that we build containing all the C code and then a handful of object files for the assembled kernels (where appropriate) in an archive that we can pass to the linker (or the user, if emitting static libraries for the user to link). The compiler will select the appropriate bitcode file for merging into our codegen-produced module, specialize the placeholder variables with target information (supported CPU features, etc), and then use normal LLVM optimizations to DCE and propagate LTO-style from the codegen calling the ukernel entry points. When finally linking we'd then include the assembled kernel archives and let the linker drop any unreferenced kernels in those object files.

An example of this flow (modulo the kernel objects) can be seen in `iree/builtins/device`:
* declaring target specialization for use either embedded in an application or via the compiler: https://github.com/google/iree/blob/65e47e77ef3ef76a2b22daf4050e9f39b6c71450/runtime/src/iree/builtins/device/device.h/#L99-L108
* defaulting the specialization when in an app: https://github.com/google/iree/blob/65e47e77ef3ef76a2b22daf4050e9f39b6c71450/runtime/src/iree/builtins/device/device_generic.c/#L9-L11
* compiler selecting the appropriate bitcode file: https://github.com/google/iree/blob/65e47e77ef3ef76a2b22daf4050e9f39b6c71450/compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/Builtins/Device.cpp/#L28-L53
* compiler overriding the target specialization: https://github.com/google/iree/blob/65e47e77ef3ef76a2b22daf4050e9f39b6c71450/compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/Builtins/Device.cpp/#L93

Some things I've identified (more hiding, but I don't think many more):

## Add `DEPS` to iree_bitcode_library to specify additional bitcode files for linking

The bitcode library rule currently just handles sources but that limits it to only depending on files in the same package (thanks, bazel). Adding a `DEPS` field that passed along additional bitcode files produced by other bitcode library rules would let us have the `ukernel/arch/` libraries linked into the base `ukernel/` code so that we get a single .bc at the end for the compiler to deal with.

## Remove use of build system templating

The `configure_file` of the config.h files won't work when we need to cross-compile multiple bitcode files in the same cmake invocation. We can swap to using compiler defines that we can supply on `DEFINES` instead in these cases.

## Switch to using late specialization of target features

e.g. https://github.com/google/iree/blob/65e47e77ef3ef76a2b22daf4050e9f39b6c71450/runtime/src/iree/builtins/ukernel/arch/arm_64/mmt4d_arm_64.c/#L17-L28 is currently something decided when compiling and would require one bitcode file per unique combination of all the preprocessor flags - switching instead to use the target specialization externs (see above) would still let us get the same selection but also make those decisions after we load the bitcode. This is identical to what CUDA does for the same reasons: https://llvm.org/docs/NVPTXUsage.html#linking-with-libdevice

Example docs here: https://github.com/iree-org/iree/tree/main/runtime/src/iree/builtins/device#link-time-configuration

When in the compiler we'll load the bitcode, specialize the flags while the kernels are still external references, run normal optimizations to prune what we don't need, and end up only requiring the kernels that are actually called during linking. When building for integration into applications we'll effectively do the same thing by making those flags compile-time constants and passing only the objects we need to the linker. If we run into any issues there we can always tweak how those flags are expressed - for example, we could instead of having a raw extern int variable instead have a macro that resolves them in the preprocessor when possible and otherwise emits the variable.

## Add iree_asm_library (or something) to produce an archive of kernels

The main ukernel library is mostly ready for bitcode but under arch/ we have a few host-config switches using check_cxx_compiler_flag and then conditionally compiling the various kernels. At least for compiler use we need to compile all of those arch assembly files to object files with our own clang that'll always support these features so the IREE compiler can select between them. I think we can find a solution that looks more like globbing and letting the linker decide vs trying to teach the compiler to select between the object files when passing them to the linker. This requires some experimentation to see what the linker does in some of these cases, but my working hypothesis is:
* assemble each .s to a .o using our clang
* archive the .o files into a single .a
* have the compiler pass the .a to the linker, which will only pull in the symbols it needs based on what the bitcode tries to call

That gives us one .a per architecture (so per arch we have a .bc for the C library and a .a for the assembly kernels) and the compiler selection logic in something like https://github.com/google/iree/blob/65e47e77ef3ef76a2b22daf4050e9f39b6c71450/compiler/src/iree/compiler/Dialect/HAL/Target/LLVM/Builtins/Device.cpp/#L28-L53 can be super simple and not need to change as new kernels/features/etc are added. I think this same approach will work for application hosting as well but may require some preprocessor goo to help it.

## Ensure visibility lets everything get pruned

We'll want to make sure when we link the bitcode into our codegen modules we're stripping everything not required as early as possible (immediately after merging, hopefully) - that way we don't end up running a lot of LLVM passes on code that'll eventually be stripped. This may mean tweaking `IREE_UK_EXPORT` when compiling standalone or something.

**Comment by allieculp** [comment]
@benvanik Setting this as P2 - please bump up if needed.

**Comment by benvanik** [comment]
Fixed by @MaheshRavishankar in #13460!
