### ISSUE TITLE
Wrong conversion of index vector to LLVM

### ISSUE THREAD

**Issue by dcaballe** [openxla/iree#12111]
This issue will break rv32 in one of our upcoming integrates. It looks like when compiling in 32-bit mode we generate a `vector<3xi32>` addition like this:

```
    %1 = llvm.mlir.constant(dense<[0, 1, 2]> : vector<3xindex>) : vector<3xi32>
    %7 = llvm.add %6, %1  : vector<3xi32>
```

and the translation from MLIR to LLVM turns that addition into `%8 = add <3 x i32> %7, <i32 0, i32 0, i32 1>`. It looks like a missing type conversion since the `index` type in the constant should have been lowered before translating to LLVM...

It has been really a pain to root-cause this :(

Full repro:

```
module {
  llvm.func @_iota_dim1_dispatch_0_generic_2x3(%arg0: !llvm.ptr<struct<"iree_hal_executable_environment_v0_t", (ptr<i32>, ptr<func<i32 (ptr<func<i32 (ptr<i8>, ptr<i8>, ptr<i8>)>>, ptr<i8>, ptr<i8>, ptr<i8>)>>, ptr<ptr<func<i32 (ptr<i8>, ptr<i8>, ptr<i8>)>>>, ptr<ptr<i8>>, struct<"iree_hal_processor_v0_t", (array<8 x i64>)>)>> {llvm.align = 16 : i64, llvm.noalias}, %arg1: !llvm.ptr<struct<"iree_hal_executable_dispatch_state_v0_t", (i32, i32, i16, i16, i32, i32, i16, i8, i8, ptr<i32>, ptr<ptr<i8>>, ptr<i32>)>> {llvm.align = 16 : i64, llvm.noalias}, %arg2: !llvm.ptr<struct<"iree_hal_executable_workgroup_state_v0_t", (i32, i32, i16, i16, i32, ptr<ptr<i8>>, i32)>> {llvm.align = 16 : i64, llvm.noalias}) -> vector<3xf32> {
    %0 = llvm.mlir.constant(0 : i32) : i32
    %1 = llvm.mlir.constant(dense<[0, 1, 2]> : vector<3xindex>) : vector<3xi32>
    %2 = llvm.load %arg2 : !llvm.ptr<struct<"iree_hal_executable_workgroup_state_v0_t", (i32, i32, i16, i16, i32, ptr<ptr<i8>>, i32)>>
    %3 = llvm.extractvalue %2[0] : !llvm.struct<"iree_hal_executable_workgroup_state_v0_t", (i32, i32, i16, i16, i32, ptr<ptr<i8>>, i32)> 
    %4 = llvm.mlir.undef : vector<3xi32>
    %5 = llvm.insertelement %3, %4[%0 : i32] : vector<3xi32>
    %6 = llvm.shufflevector %5, %4 [0, 0, 0] : vector<3xi32> 
    %7 = llvm.add %6, %1  : vector<3xi32>
    %8 = llvm.sitofp %7 : vector<3xi32> to vector<3xf32>
    llvm.return %8 : vector<3xf32>
  }
}
```

mlir-translate repro.mlir -mlir-to-llvmir

Output
```
define <3 x float> @_iota_dim1_dispatch_0_generic_2x3(ptr noalias align 16 %0, ptr noalias align 16 %1, ptr noalias align 16 %2) {
  %4 = load %iree_hal_executable_workgroup_state_v0_t, ptr %2, align 8
  %5 = extractvalue %iree_hal_executable_workgroup_state_v0_t %4, 0
  %6 = insertelement <3 x i32> undef, i32 %5, i32 0
  %7 = shufflevector <3 x i32> %6, <3 x i32> undef, <3 x i32> zeroinitializer
  %8 = add <3 x i32> %7, <i32 0, i32 0, i32 1>
  %9 = sitofp <3 x i32> %8 to <3 x float>
  ret <3 x float> %9
}
```

**Comment by dcaballe** [comment]
Will mirror this on the MLIR side

**Comment by benvanik** [comment]
That repro input already seems like it's bad? Where does that constant come from?
`%1 = llvm.mlir.constant(dense<[0, 1, 2]> : vector<3xindex>) : vector<3xi32>` <- that attribute shouldn't be `vector<3xindex>` but `vector<3xi32>`

**Comment by dcaballe** [comment]
Yes, that's what I mentioned above. It looks like a missing type conversion when we lower the index type to llvm. Actually, if we do: `mlir-opt --convert-index-to-llvm=index-bitwidth=32 repro.mlir`, the index type is not lowered.

**Comment by benvanik** [comment]
Was just pointing out that your repro.mlir in the llvm dialect is already bad so it isn't really a repro, just an example failure :) Seeing whatever the IR before that is would be useful in figuring out if this is coming from something like mhlo->linalg or whatnot earlier on. In other words, work back from what produces that llvm.mlir.constant op with the bad attribute type.

**Comment by dcaballe** [comment]
Fixed by https://github.com/llvm/llvm-project/issues/60614
