### ISSUE TITLE
RESOURCE_EXHAUSTED; overflowed timeline semaphore max value

### ISSUE THREAD

**Issue by powderluv** [openxla/iree#12122]
### What happened?

SHARK SD users are reporting hitting `RESOURCE_EXHAUSTED; overflowed timeline semaphore max value`  while running SHARK on Vulkan. 

### Steps to reproduce your issue

Download the latest SHARK WebUI .exe https://github.com/nod-ai/SHARK/releases/tag/20230208.509

Run on a 6600, 6800XT or Quadro RTX 5000 (may happen on others too).  

On my Quadro it is easy to hit this issue if you compile for the `rdna2-unknown-unknown` target triple.

```
PS C:\Users\anush\Downloads> .\shark_sd_20230208_508.exe --iree-vulkan-target-triple=rdna2-unknown-linux 
```

```
RuntimeError: Error invoking function: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\native_semaphore.cc:155: RESOURCE_EXHAUSTED; overflowed timeline semaphore max value; while invoking native function hal.fence.await; while calling import;
[ 1]   native hal.fence.await:0 -
```

**Comment by powderluv** [comment]
(other users are reporting on AMD 6800XT and 6600) https://discord.com/channels/973663919757492264/1062812824411328542/1067450299628912650
https://discord.com/channels/973663919757492264/975522729564446740/1070803338658062417
https://discord.com/channels/973663919757492264/973663920290164818/1073082042625048616
and it looks like "it has been working all day" and then it happens

**Comment by powderluv** [comment]
Here are some values for it:

```
(shark.venv) PS C:\g\shark> vulkaninfo  | findstr deviceName
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
        deviceName        = AMD Radeon RX 7900 XTX
(shark.venv) PS C:\g\shark> vulkaninfo  | findstr maxTimelineSemaphoreValueDifference
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
        maxTimelineSemaphoreValueDifference = 4294967295
        maxTimelineSemaphoreValueDifference                  = 4294967295
       
        ```

```
PS C:\Users\anush\Downloads> vulkaninfo | findstr deviceName
        deviceName        = Intel(R) UHD Graphics 630
        deviceName        = Intel(R) Arc(TM) A770 Graphics
        deviceName        = Quadro RTX 5000
        deviceName        = Intel(R) UHD Graphics 630
PS C:\Users\anush\Downloads> vulkaninfo | findstr maxTimelineSemaphoreValueDifference
        maxTimelineSemaphoreValueDifference = 18446744073709551615
        maxTimelineSemaphoreValueDifference                  = 18446744073709551615
        maxTimelineSemaphoreValueDifference = 18446744073709551615
        maxTimelineSemaphoreValueDifference                  = 18446744073709551615
        maxTimelineSemaphoreValueDifference = 2147483647
        maxTimelineSemaphoreValueDifference                  = 2147483647
        maxTimelineSemaphoreValueDifference = 18446744073709551615
        maxTimelineSemaphoreValueDifference                  = 18446744073709551615
        ```

**Comment by ScottTodd** [comment]
`maxTimelineSemaphoreValueDifference` (value _difference_) is different from overflowing the max value.
Here are stats for the value difference: https://vulkan.gpuinfo.org/displayextensionproperty.php?extensionname=VK_KHR_timeline_semaphore&extensionproperty=maxTimelineSemaphoreValueDifference&platform=all

Here is our code for overflowing the max value: https://github.com/iree-org/iree/blob/78940a262083d274575709e292c859cd5655adee/runtime/src/iree/hal/drivers/vulkan/native_semaphore.cc#L19-L37 https://github.com/iree-org/iree/blob/78940a262083d274575709e292c859cd5655adee/runtime/src/iree/hal/drivers/vulkan/native_semaphore.cc#L149-L160 https://github.com/iree-org/iree/blob/78940a262083d274575709e292c859cd5655adee/runtime/src/iree/hal/drivers/vulkan/native_semaphore.cc#L215-L219

This might be hiding another failure if the application is ignoring an error and continuing anyway (or the error reporting is not running / running in the right sequence).

**Comment by powderluv** [comment]
is there anything we can enable in our builds to get more debug info ?

**Comment by powderluv** [comment]
One end is unable to recreate the issue with running with iree-benchmark-module. Will keep trying to narrow down.

**Comment by paperplanet** [comment]
I have encountered this same semaphore overflow error when running vae model with nvidia rtx3050 through vulkan api on windows. And after some trial, I managed to workround this issue by adding `--vulkan_dedicated_compute_queue=1` parameter in iree-run-module arguments. My final command becomes: `iree-run-module --module=vae77_512_512_fp16_stabilityai_stable_diffusion_2_1_base.vmfb --function=forward --device=vulkan --input=1x4x64x64xf16 --vulkan_dedicated_compute_queue=1 --output=@vae_o0.npy`. Hope that information can help.
`

**Comment by powderluv** [comment]
Thank you for the workaround is there any performance impact with that flag?

**Comment by benvanik** [comment]
I believe we originally had this on but disabled it and started using the graphics queue due to performance issues on AMD you found. I suspect this is helping here because the compute queue can run longer tasks than the graphics queue (no need for canceling the work in order to avoid the GUI from janking). We'd need someone to do some benchmarking across vendors and device family to see what we should make the default - if only AMD benefits from the graphics queue but not ARM/Nvidia/etc then we could limit it to there. That said, it'd be good to get confirmation from any vendor this is what's happening (compute queue has higher timeout allowances).

**Comment by paperplanet** [comment]
> Thank you for the workaround is there any performance impact with that flag?

Currently I do not have a decent AMD card which I can analyze the performance impact with. But I think it would be great if we can have this parameter adjustable from shark's frontend for greater compatibility.

**Comment by ScottTodd** [comment]
Can we call this issue obsolete/fixed, or are users still experiencing issues?

**Comment by ScottTodd** [comment]
Let's close and re-open if there are more reports of this.
