### ISSUE TITLE
Clean up GCC warning flags

### ISSUE THREAD

**Issue by stellaraccident** [openxla/iree#4432]
We build production releases for Linux with GCC, and the warnings are clearly not tweaked, especially on the bazel side. See a recent action: https://github.com/google/iree/runs/1668069561?check_suite_focus=true

**Comment by GMNGeoffrey** [comment]
Probably also helped by #9306

**Comment by ScottTodd** [comment]
https://github.com/openxla/iree/issues/14507 has some specific details. Closing this as duplicate.
