### ISSUE TITLE
Reproducers of python tests are not runnable with IREE tools (missing passes)

### ISSUE THREAD

**Issue by GMNGeoffrey** [openxla/iree#4757]
**Describe the bug**
Reproducers of python tests are not runnable with IREE tools. Discovered by @joker-eph 

**To Reproduce**
Attempt to run this pipeline with iree-tf-opt or iree-opt-tflite (why do the names not match?), which comes from the test layers_dynamic_dims_tests__layer__Dot__target_backends__tflite

```
'func(tf-executor-graph-pruning{ops-to-preserve=}, tf-executor-island-coarsening, tf-materialize-passthrough-op, canonicalize), tf-shape-inference{max-iterations=10}, symbol-dce, func(tf-optimize, cse, tf-device-index-selector), canonicalize, tf-shape-inference{max-iterations=10}, tf-functional-control-flow-to-regions, func(tf-device-decompose-resource-ops), tfl-prepare-composite-funcs-tf, tf-region-control-flow-to-functional, inline{default-pipeline=canonicalize max-iterations=4 op-pipelines=}, symbol-dce, tfl-lower-static-tensor-list{allow-tensorlist-pass-through=false}, tf-saved-model-optimize-global-tensors, tf-shape-inference{max-iterations=10}, tfl-legalize-tf-while, inline{default-pipeline=canonicalize max-iterations=4 op-pipelines=}, func(tf-decode-constant, canonicalize, cse), symbol-dce, tf-saved-model-freeze-global-tensors{allow-mutable-tensors=false}, tf-shape-inference{max-iterations=10}, func(tf-layout-assignment{force-data-format=NHWC}, tf-move-transposes{direction=end fold-transpose-in-ops=false}, tf-move-transposes{direction=begin fold-transpose-in-ops=false}, tfl-prepare-tf{tfl-allow-bf16-and-f16-type-legalization=false tfl-unfold-batch-matmul=true}, canonicalize), tf-shape-inference{max-iterations=10}, inline{default-pipeline=canonicalize max-iterations=4 op-pipelines=}, func(tf-init-text-file-to-import, tfl-legalize-tf{run-tfl-runtime-verification=true}, tfl-optimize), tfl-optimize-functional-ops, func(tfl-raise-custom-ops), symbol-dce, func(canonicalize, cse, tfl-split-merged-operands), tfl-insert-call-once-op, tfl-while-loop-outline, func(tfl-runtime-verify)' -verify-each
```

Or really, just `--pass-pipeline="func(tf-executor-graph-pruning{ops-to-preserve=})"`

MLIR Textual PassPipeline Parser:1:6: error: 'tf-executor-graph-pruning' does not refer to a registered pass or pass pipeline

More generally, we should ensure that this can't occur, either by having the Python use the same tools that a user would use in the reproducer, or by making the registration use some shared structure so that adding something in one place means adding it the other.

**Comment by GMNGeoffrey** [comment]
Assigning to you @benvanik since I believe you just trimmed the pass registration

**Comment by benvanik** [comment]
Names are different for legacy reasons - iree-tf-import needs to be renamed to iree-import-tf. I think Stella didn't want to break anything when initially landing the new tflite/xla tools and changing it is TODO.

It's expected that you can't run tensorflow passes with iree-opt-**tflite** - that's strictly for *tflite*.

As far as I know I didn't remove anything from iree-tf-import:
https://github.com/google/iree/commit/000d64f50538ad381731263e81008e0f02cd5e8d#diff-280436dfc64df86f44423fd6ec5585558abca70f124d14763f84a76a87652390

Did this ever work?

**Comment by GMNGeoffrey** [comment]
Yeah iree-tf-opt was my first guess, but I decided to try with the other, since this is a tflite test. Maybe it never worked.

**Comment by benvanik** [comment]
Not seeing anything obvious here in diffs - I don't know anything about the python layer/reproducers but agree that they should provide the same input as expected to the other tools.

**Comment by benvanik** [comment]
I still don't really understand pass registration and such, but the deps on the rules stayed the same (https://github.com/google/iree/blob/000d64f50538ad381731263e81008e0f02cd5e8d/integrations/tensorflow/iree_tf_compiler/TF/BUILD#L0-L1) during the move so if they are coming in via automagic then it's just possible these were never linked in/registered.

**Comment by benvanik** [comment]
We don't even use tf-executor-graph-pruning, so that must be getting pulled in from some tf pass pipeline.

**Comment by benvanik** [comment]
I just suspect no one ever set these tools up for doing anything but running our pipeline and not as generic opt tool.

**Comment by GMNGeoffrey** [comment]
Closing this as obsolete
