### ISSUE TITLE
Extra dependencies in top-level tools

### ISSUE THREAD

**Issue by GMNGeoffrey** [openxla/iree#5085]
Some dependencies have sneaked in to our top-level tools that really should be at least isolated to lower-down targets. These came in during an LLVM integrate: https://github.com/google/iree/commit/ce85ce5c31170cd2fdee812baf85bc3b880264ff. We should not be calling `registerLLVMDialectTranslation` in main of `iree-run-mlir` and `iree-translate`

See https://github.com/google/iree/pull/4952 and https://github.com/google/iree/pull/5081 where the dependencies were propagated to the CMake build.

**Comment by ScottTodd** [comment]
Looks like these deps still exist

https://github.com/google/iree/blob/9a50d728bdc23d6dc472a30fc413a3bce42aa9a2/iree/tools/iree_translate_lib.cc#L43-L47

Still worth pruning, or accept that the compiler tools will be bloated? :P

**Comment by benvanik** [comment]
We do have cmake flags for these now that we could use to prune them down - the biggest one being LLVM dialects - could time a build with/without that and see if it makes a difference.

**Comment by GMNGeoffrey** [comment]
These are no longer present AFAICT
