### ISSUE TITLE
Documentation on Linalg on tensors codegen pipeline

### ISSUE THREAD

**Issue by hanhanW** [openxla/iree#5300]
We have a [documentation](https://google.github.io/iree/design-docs/codegen-passes) on current codegen pipeline. I think it's good to have a documentation for Linalg on tensors, since it is also more complicated and will be our default pipeline. We can start it after #5043.

File an issue for tracking it.

cc @MaheshRavishankar @antiagainst @asaadaldien @ThomasRaoux

**Comment by tymsai** [comment]
Need some more info.

**Comment by ScottTodd** [comment]
Maybe we can call this fixed after the MLIR Open Design Meeting discussion:
2021-07-15: From MHLO To Linalg in IREE ; [slides](https://mlir.llvm.org/OpenMeetings/2021-07-15-From-MHLO-To-Linalg-in-IREE.pdf) - [recording](https://youtu.be/GkorNMHPFPI)
(see others at https://mlir.llvm.org/talks/)

The https://github.com/iree-org/iree/blob/main/docs/developers/design_docs/codegen_passes.md page is still out of date though. Could be worth a little cleanup pass through that at least redirects to that talk.
