### ISSUE TITLE
Importing an unavailable exported_name from TF doesn't error

### ISSUE THREAD

**Issue by phoenix-meadowlark** [openxla/iree#5303]
Asking to compile an exported name that doesn't exist in a saved module / module should throw an error, but currently doesn't. This can be confusing when `tf.function`s are created, but silently fail to save or load during saved model creation/loading.

```python
class AddModule(tf.Module):

  def add(self, a, b):
    return a + b

# Returns an empty module because 'add' is not a tf.function
asm = iree.compiler.tf.compile_module(
    AddModule(), import_only=True, exported_names=["add"])
print(asm.decode("utf-8"))
```

```mlir
"module"() ( {
  "module_terminator"() : () -> () loc(#loc)
}) : () -> () loc(#loc)
#loc = loc(unknown)
```

**Comment by alliemartens** [comment]
Routing to @jpienaar and @rsuderman to asses and add priority if needed.

**Comment by alliemartens** [comment]
@not-jenni Can you add priority to this while on frontend rotation?

**Comment by aaron-schneider** [comment]
Ho there! This bug hasn't been updated in a long time. Good intentions and all, but we're moving this to the backlog. Feel free to bring it back if you think there's a reasonable chance it'll get worked on in the next 6mo!

**Comment by ScottTodd** [comment]
Going to call this obsolete, as the TensorFlow export APIs have changed a few times and the TensorFlow frontend is a lower priority.
