### ISSUE TITLE
[New documentation] Write docs for "TensorFlow Lite bindings"

### ISSUE THREAD

**Issue by ScottTodd** [openxla/iree#5462]
* Live preview of this page: https://scotttodd.github.io/iree/bindings/tensorflow-lite/, which will eventually live on https://google.github.io/iree/ after we switch over the docs.
* ~~Source currently lives on the `staging-docs-rework` branch here: https://github.com/google/iree/blob/staging-docs-rework/mkdocs/docs/bindings/tensorflow-lite.md . PRs or direct commits to the branch are okay. We'll want to be careful about force pushes / rebases though.~~
  Source lives in https://github.com/google/iree/blob/main/docs/website/docs/bindings/tensorflow-lite.md
* See the README here for instructions on previewing changes locally: ~~https://github.com/google/iree/tree/staging-docs-rework/mkdocs~~ https://github.com/google/iree/tree/main/docs/website

This will connect in some places with the corresponding frontend documentation (tracking issue: https://github.com/google/iree/issues/5455) and could discuss both the C API [bindings/tflite](https://github.com/google/iree/tree/main/bindings/tflite) and the Java API (https://github.com/google/iree/pull/5361).

We should specifically speak to the pros/cons of using these bindings over the alternatives.

If this is still being built / is unstable, we could omit the pages from the documentation site at first.

**Comment by aaron-schneider** [comment]
Ho there! This bug hasn't been updated in a long time. Good intentions and all, but we're moving this to the backlog. Feel free to bring it back if you think there's a reasonable chance it'll get worked on in the next 6mo!
