### ISSUE TITLE
Reduce op test flakey on Vulkan and VMVX in the TOSA dialect

### ISSUE THREAD

**Issue by not-jenni** [openxla/iree#5885]
The cmake_linux_x86-swiftshader check is failing at https://github.com/google/iree/commit/68bb0cb6bfa823d03b66502a8e374cffb3691b44 for `iree/test/e2e/tosa_ops/check_vmvx_vmvx_reduce.mlir`

https://source.cloud.google.com/results/invocations/fd5e6ba3-c6a0-479c-805f-9542b1cb4052/targets/iree%2Fgcp_ubuntu%2Fcmake%2Flinux%2Fx86-swiftshader%2Fmain/log

I will add the test to the exclusions for now

**Comment by GMNGeoffrey** [comment]
This appears to be flakey, actually: https://source.cloud.google.com/results/invocations/fb681ef7-496a-4682-a0c2-c202f83c3852/targets

1% flakes :fearful: The output isn't consistent in its wrongness either. Looks like it's writing just random garbage to the output buffer.

**Comment by GMNGeoffrey** [comment]
On Vulkan some of the tests always fail and some are flakey: https://source.cloud.google.com/results/invocations/5fa93730-84f2-4cb6-b530-7e6a81dde8e2/targets

**Comment by benvanik** [comment]
Cool - that looks similar then - values will differ because of allocator differences, but the fact that they fail with randomish values bodes well for this being a common codegen issue.

**Comment by GMNGeoffrey** [comment]
Oh and just for completeness, LLVM passes 1000/1000 times: https://source.cloud.google.com/results/invocations/6a18d9de-3639-4eaa-9b97-1a08727a9411

**Comment by antiagainst** [comment]
Don't think this is an issue anymore -- TOSA reduction is enabled in tests for both.
