### ISSUE TITLE
Float->int rounding behavior needs better definition.

### ISSUE THREAD

**Issue by benvanik** [openxla/iree#6160]
[XLA's spec](https://www.tensorflow.org/xla/operation_semantics#convertelementtype) says:
"Note: The precise float-to-int and visa-versa conversions are currently unspecified, but may become additional arguments to the convert operation in the future. Not all possible conversions have been implemented for all targets."

If we are fine with that then we should not be testing for a particular behavior like here:
https://github.com/google/iree/blob/ccc47e8fc255bb272a5bc8336fb17c6a6ff109bf/iree/test/e2e/xla_ops/convert.mlir#L52-L57

If rounding to nearest away from zero (ala C's roundf) then -10.5 -> -11, but if rounding to even (XLA's implicit default) -10.5 -> -10.

I'm disabling the test for now until we can figure out how we want to handle it consistently across all backends - or not.

**Comment by jpienaar** [comment]
Will be handled in https://github.com/openxla/stablehlo/issues/180
