### ISSUE TITLE
```iree_tools*-win*.whl``` missing on Windows

### ISSUE THREAD

**Issue by KKimj** [openxla/iree#6417]
Hello,
Please [release](https://github.com/google/iree/releases), iree_tools for windows?
Thanks!

![image](https://user-images.githubusercontent.com/40026920/125052238-b5a84f00-e0de-11eb-9c14-f59ec5c2c85f.png)

**Comment by stellaraccident** [comment]
It attempts to build every day but it has been extremely hard to keep the
automation working for doing windows Tensorflow builds. I'm not sure when
we will have the time to invest in it again, but knowing that someone is
interested in it does help make the case.

**Comment by KKimj** [comment]
Oh, I see!
I'll keep that in mind.
If I have any new ideas, I will give you a comment.
Thank you.

**Comment by stellaraccident** [comment]
It can usually be built locally with some fiddling, as described in the
docs. It is just that Tensorflow's build system barely supports Windows and
it has been quite hard to get GitHub actions runners in a state where it
doesn't trip over something. So far we haven't had the time or motivation
to set up custom runners for these kinds of releases -- and every hour
spent on it is an hour not spent on getting the core product to a good
level of completion.

**Comment by KKimj** [comment]
Thank you.
I didn't mean to waste your time.

I mistook it for simply changing the 'release setting'.

I hope you have a good day.

**Comment by stellaraccident** [comment]
No problem at all - it is not a time waste. I myself use and develop on
windows and have been sorely frustrated by this :(

**Comment by rnett** [comment]
Running into this as well.  We're building tensorflow from source on GitHub actions for https://github.com/tensorflow/java, your build is likely more complicated than ours but it might help.  Not sure how lightly coupled XLA is any more but we ran into https://github.com/tensorflow/tensorflow/issues/50458, too.

**Comment by ScottTodd** [comment]
It's been a while, but our 'tools' packages no longer have a C++ source dependency on TensorFlow, so we can build them reliably on Windows now. I filed https://github.com/openxla/iree/issues/13484 to start building and publishing packages for Windows in general, and as part of that we can include the 'tools' wheels too.

**Comment by KKimj** [comment]
@ScottTodd 
Thank you for your hard work for a long time.
I'll be waiting for Windows release.
Thank you.
