### ISSUE TITLE
Update docs for tracing, replay and benchmarking

### ISSUE THREAD

**Issue by stellaraccident** [openxla/iree#6688]
Users are following the existing benchmarking docs here: https://github.com/google/iree/blob/main/docs/developers/developing_iree/benchmarking.md#executable-benchmarks , which describe a really low-level, compiler writers tool for benchmarking. Given that it is not a general purpose thing, folks are having problems. We should de-emphasize this path and warn that it is intended for advanced use, typically in conjunction with hand-coding input IR, etc.

In its place, we should document and provide example usage for the tracing tooling, which has a shell of a document here: https://github.com/google/iree/blob/main/bindings/python/iree/runtime/README.md

We should blow that up in the real docs with full samples and document the use of the corresponding iree-benchmark-trace and iree-run-trace tools. Bonus points for having an easy entry point to hook tracy up to it for more detailed introspection.

**Comment by ScottTodd** [comment]
Some notes from trying to use the invocation tracing:

1) Colab currently uses PyYAML version 3.13, which gave me a `TypeError: dump_all() got an unexpected keyword argument 'sort_keys'` error when tracing invocations. That's fixable by running `!pip3 install --upgrade pyyaml`, or we can check with the Colab team to see about updating the default version.

2) I was looking at the trace record / replay functionality as a way to generate inputs in Colab+Python then run tools on Windows natively. This worked (after rewriting `path: module.vmfb` to my local path - at least the yaml file was very easy to edit), but the only output from `iree-run-trace` was `--- CALL[module.main] ---`, when I was hoping to see the output values.

3) There's a bit of overlap between `iree-run-module` and `iree-run-trace` and I'm wondering if we can merge them. In particular, I'd like the `--print_statistics` flag from `iree-run-module` to also work with `iree-run-trace`.

**Comment by ScottTodd** [comment]
This is obsolete with https://github.com/openxla/iree/pull/16134 / https://groups.google.com/g/iree-discuss/c/XDNNIRq3mAU/m/4qnvuEL5AgAJ (removing YAML tracing tooling).

Other general documentation improvements for benchmarking/profiling are also tracked in https://github.com/openxla/iree/issues/14470.

A replacement for the YAML tracing sort of exists with MLIR calls and multiple modules. That could be documented too.
