### ISSUE TITLE
Lacking error messages in DispatchLinalgOnTensors pass

### ISSUE THREAD

**Issue by hanhanW** [openxla/iree#7122]
I'm implementing linalg_ext.reverse op and found that the error messages are not clear in DispatchLinalgOnTensors pass.

We expect all the operations are tiled and distributed in `DispatchLinalgOnTensors` pass. Or at least we should get some error messages. Currently, the program won't raise errors if a LinalgExt op is not tilable. This is because of the `hasOnlyDimUses ` check:

https://github.com/google/iree/blob/c8736bfa395dd86aa1678a0550e540e77d8b9d35/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp#L797-L800

There might be other issues. What I've seen is that it will return in this check, so we are not aware that the tiling implementation is not done yet.

It's better that we have more clear messages or verifications after the pass. If we keep running the program, we will see an error in very late stage, which does not reflect the actual issue.

**Comment by MaheshRavishankar** [comment]
Really old and this pass doesnt exist anymore. Closing
