### ISSUE TITLE
Collect comparison benchmarks from other systems

### ISSUE THREAD

**Issue by GMNGeoffrey** [openxla/iree#7224]
We want to be able to compare how IREE is doing vs relevant alternative systems. For now that likely means TVM and TFLite. We need a way to periodically collect this information.

Considerations
* Right now, getting a TFLite benchmark means finding someone with a phone and then running a series of steps. This should at least be turned into a script.
* It would be nice to not require someone have access to matching hardware for doing the benchmarking
* It would be nice to have this in a similar graph format as our own benchmarks
* We don't want to get regression notifications for these benchmarks
* TFLite uses XNNPack by default now, but that makes quite a few constraining assumptions about matmuls. Given that we're not yet aiming for that level of specialization, it may be more useful to measure vs TFLite with XNNPack turned off. These numbers shouldn't be taken out of context to be about TFLite performance. It may or may not be useful to have TFLite benchmarks with and without XNNPack
* We need to figure out how to benchmark a TVM model. I assume this would be for desktop only. Again, we want to be able to benchmark this on the same hardware.
* If we put these in Dana, we should make sure they're clearly separated and labeled.
* We don't want to pollute our build infrastructure with configuration of other projects. This should probably all be done with totally separate scripting.
* We need to make sure we have a way to get the same model source for all benchmarks, even if they may take them in a slightly different format.
* It may be useful to compare the results of the model runs to ensure we really are testing the same model.

I think it should be possible to upload these benchmarks to Dana, but either turn off regression monitoring or effectively do so by setting the threshold very high. We probably don't want to run these every time, so we could set up a different pipeline to do this (or make the existing pipeline check some throttle to do it, which would be a bit hacky, but might enable additional reuse).

For now though, the first step would be scripts to do this manually, but repeatably.

FYI @antiagainst @julianwa

**Comment by ScottTodd** [comment]
This issue looks obsolete. There are some comparative benchmarks in https://github.com/openxla/openxla-benchmark/tree/main/comparative_benchmark now. I think there are also several other out of tree / ad-hoc comparative benchmark efforts. Not sure how useful it would be to keep tracking those projects in this repo itself.
