### ISSUE TITLE
Make pull request benchmarking more stable and indicative

### ISSUE THREAD

**Issue by antiagainst** [openxla/iree#7342]
We are seeing stability issues when benchmarking. This is partially because of the phones in the lab, as we should root and pin down CPU/GPU frequency there when appropriate. That is captured by https://github.com/google/iree/issues/6521. 

Aside from that, for pull request benchmarking, we also have other issues with stability, which renders it less usable and indicative as it should be. Concretely, as of today, we just run all benchmarks and get average once, and [compare with the latest remote branch tip](https://github.com/google/iree/blob/93e4f7e7ac22111f204900b61f99785c0955c005/build_tools/benchmarks/post_benchmarks_as_pr_comment.py#L142-L160) numbers. This is one data point to one data point comparison. This is different from the Dashboard, where one data point pushed to it won't immediately trigger regression/improvement classifications. Instead we need at least 3 consecutive data points to be higher/lower than the previous average with a threshold. So it's resilient to one-off outliers. 

We should consider moving the pull request benchmark analysis to be close to the dashboard for consistency:

1) We can consider run the benchmark multiple runs and get multiple averages and remove outliers, etc. This would mean to reduce the benchmarks run on pull request; otherwise it would take a long time. But that's fine as lots of the configurations are just permutations over, like, the number of threads; they should in general move in a coherent way. We don't need the full scale there to tell regression/improvements. This needs to modify the scripts to support general filters, like https://github.com/google/iree/pull/7246.

2) We can consider adding APIs to Dana to allow querying the current average (and potentially other useful analysis done on historical data), so that we can compare with that, instead of one commit's result (which can be an outlier).

**Comment by GMNGeoffrey** [comment]
We should be writing benchmark data to an easily-queryable cloud database, which would allow us to query it without futzing with Dana APIs. We should also query the merge-base of the PR, not the current head, since that will include changes since after the PR branch was split off. We can bring Dana back into the equation if we want something that's based on analysis of multiple runs, as in (2) above (the database would be useful regardless).

**Comment by ScottTodd** [comment]
Hey @pzread this looks related to some of your other recent work. Want to close this issue as obsolete, or keep it open?

**Comment by pzread** [comment]
I think we can close this one. The follow-up works on Android benchmarks can be tracked in https://github.com/openxla/iree/issues/15452
