### ISSUE TITLE
Move the XLA sanitization passes from iree-import-xla to the core pipeline.

### ISSUE THREAD

**Issue by stellaraccident** [openxla/iree#7713]
Now that JAX can emit MLIR/MHLO directly, we can kill iree-xla-import. Or we could if we move a few bits into the core MHLO conversion related to sanitizing XLA inputs (tuple expansion, etc).

**Comment by alliemartens** [comment]
@stellaraccident Still an active issue or no?

**Comment by rsuderman** [comment]
We can completely delete the `iree-import-xla` tool once the iree-jax changes land. Hoping to delete this week.

**Comment by stellaraccident** [comment]
@rsuderman Still appears to be there. Can we delete/close this issue?

**Comment by jpienaar** [comment]
Done in #12898
