### ISSUE TITLE
Implement SPIR-V archives for combining shader modules.

### ISSUE THREAD

**Issue by benvanik** [openxla/iree#7824]
(this same approach could be used for WebGPU and the same concept can be used for Metal but [using their archiver instead of our flatbuffers](https://developer.apple.com/documentation/metal/libraries/building_a_library_with_metal_s_command-line_tools))

Today we are turning each dispatch region into an executable and then carrying that separation all the way through to runtime. This means that the VM code we produce has to juggling sometimes 1000+ executables and that we need to maintain and track those at runtime. The independent executables also make things like asynchronous compilation and caching much trickier as we don't have full visibility into the shader modules or pipelines we need to compile at the same time.

The idea here is to extend https://github.com/google/iree/blob/552d3f888e46f96c8227b1bd2e4600b85338237b/iree/schemas/spirv_executable_def.fbs such that it has a `SpirVArchiveDef` that exposes the `entry_points` and then a set of `SpirVShaderModuleDefs`s that each entry point is mapped in to:
![image](https://user-images.githubusercontent.com/75337/144935804-10a53317-9a03-43e6-9437-d4e152b66d52.png)
(the specialization constants should be per entry point, and eventually we'll move those to the hal proper)

At runtime we'd replace the https://github.com/google/iree/blob/b998f1f8ebcdb80aa07217a9413f8ecc63ba545e/iree/hal/vulkan/native_executable.cc with an archive_executable (or something) that ran through the flatbuffer and issued the vkCreateShaderModule for each in the file and then created the pipelines as it does today using the appropriate shader module for each entry point.
This process could then be extended to perform all shader module and pipeline creation on worker threads in parallel (in future revisions) or in the case of WebGPU we'd use the async APIs to do the compilation.

The thing to resolve in the compiler is that currently our hal.executables contain a `builtin.module` with a single nested `spv.module` and the existing linking code combines the functions into the same `spv.module`:
https://github.com/google/iree/blob/fd51378b1858b42e58651e4ab58cbf948cfab7c1/iree/compiler/Dialect/HAL/Target/VulkanSPIRV/test/linking.mlir#L144-L161

instead, we should nest multiple `spv.module`s into the outer module:
```mlir
hal.executable.variant {
  module {
    spv.module {
      spv.func
    }
    spv.module {
      spv.func
    }
  }
}
```
and have the serialization code pull them out to build the flatbuffer. This may require some pass scoping tweaks in the spirv codegen pipeline but likely not many.

**Comment by nihui** [comment]
afaik, multiple entry point in one shader module did not work with moltenvk when I tried this approach two years ago. so in ncnn library, the one shader one entry point rule is still applied for better cross platform compatibility. I wonder if the issue has been resolved now.

**Comment by benvanik** [comment]
Awesome - that's helpful (and what I worried about)! This approach would let us work around that as each entry point would have its own shader module (if we needed), so even more reason not to do #7823 (that makes multiple entry points). It'd of course be good if these things worked as speced, but that's a battle for another day :)

**Comment by antiagainst** [comment]
Thanks Ben for the tracking issue! I'll address this after clearing up the current work queue.

Yeah, this is the other side of standards with lots of implementations; it just takes a super long time to have a feature propagated. It's meant to address the shader permutation issue (to some extent); but I guess until the majorities of the game engines are taking full leverage of it, it's still gonna be problematic here and there in drivers.. :(

**Comment by benvanik** [comment]
Fun post here showing MTLLibrary timings: https://github.com/gpuweb/gpuweb/issues/1064
(ideally we'd not have a flatbuffer for metal at all and just pack MTLLibrary's directly)
WGSL will need the same approach as SPIR-V here with multiple modules per executable - I've added that in #7849 and it's something we can change the SPIR-V flatbuffer to look like:

```
// Contents of one WGPUShaderModule, possibly with multiple entry points.
// Entry points have the name "dN" where N is the executable-wide entry point
// ordinal.
table WGSLShaderModuleDef {
  // WGSL source code.
  code:string;

  // Optional `source-map-v3` format source map.
  source_map:string;
}

table WGSLExecutableDef {
  // An ordered list of shader modules, each containing 1+ entry points.
  shader_modules:[WGSLShaderModuleDef];

  // A mapping of executable entry point ordinals to the shader module in which
  // they reside.
  entry_points:[int];
}
```

**Comment by alliemartens** [comment]
@benvanik @antiagainst @ScottTodd Checking in on P1 issues, this hasn't been touched for 8 months. Do we plan to work on it or can we push to P2?

**Comment by antiagainst** [comment]
I don't think there is immediate plans for this right now; so fine to drop to P2 to me.
