### ISSUE TITLE
Improve flows for users reporting issues

### ISSUE THREAD

**Issue by GMNGeoffrey** [openxla/iree#7890]
- [x] Most issues users file aren't really bugs, we should have a template for "user report" or something
- [ ] The instructions regarding reproducing with tensorflow are very outdated
- [ ] We should have instructions for determining if something is an MHLO bug and filing in the MHLO component
- [ ] We should be able to provide issue report instructions in the diagnostics from pass failures, e.g. the MHLO->Linalg pass could direct people to try reproducing with the upstream MHLO passes

**Comment by ScottTodd** [comment]
Oh neat, GitHub has "issue forms" now too:
* https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/
* https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by benvanik** [comment]
oo issue forms look neat

**Comment by ScottTodd** [comment]
Yeah, forms have a really nice UI. I'd like to try them out a bit and then add a few templates. We probably shouldn't have too many templates though... maybe
* build issues
* general question / feature request
* bug / missing op coverage / etc.

then we'd continue to use blank issues (no template) for work tracking?

**Comment by ScottTodd** [comment]
Issue reporting templates are updated now. Maybe someone more familiar with MHLO / TOSA / frontends could refresh our docs on how to generate good compiler bug reports.

**Comment by ScottTodd** [comment]
Could still use docs on how to effectively report frontend bugs, but I don't think this stale issue is helping us make progress on that. Could maybe file new issues in torch-mlir, SHARK-Turbine, JAX, TensorFlow, etc.
