### ISSUE TITLE
`tfl.unidirectional_lstm` needs stateful decomposition to other TFLite operations

### ISSUE THREAD

**Issue by rsuderman** [openxla/iree#8128]
[Keras](https://github.com/google/iree-samples/blob/main/tflitehub/keras_ocr_test.py) contains a `tfl.unidirectional_lstm` operation. These model can be simplified to a series of TFLite and stateful operations.

Including these decompositions should help to lower to TOSA.

**Comment by jpienaar** [comment]
@rsuderman I believe you've been looking in this area recently, not sure If premature to mark as in progress.

**Comment by sg-vlsi-experiment** [comment]
Hi there, is there any progress on this issue? Thanks

**Comment by ScottTodd** [comment]
This issue is very old and IREE no longer directly consumes `tfl` ops. Maybe re-file an issue on https://github.com/tensorflow/tensorflow or https://github.com/openxla/stablehlo?
