### ISSUE TITLE
Create automated LLVM bump action

### ISSUE THREAD

**Issue by stellaraccident** [openxla/iree#8187]
It would be nice if we had a GitHub action which periodically attempted to bump LLVM, creating a PR that we can just submit on green (or take over and patch). Would be a good way to stay ahead of things and know when big things need attention.

**Comment by ScottTodd** [comment]
https://github.com/shark-infra/megabump/ (and the bot: https://github.com/shark-infra/megabump/tree/bot) are attempts to solve this. Let's close this issue?
