### ISSUE TITLE
Update e2e_benchmarking.md doc

### ISSUE THREAD

**Issue by dcaballe** [openxla/iree#9076]
An external user reported that [e2d_benchmarking.md](https://github.com/google/iree/blob/main/docs/developers/developing_iree/e2e_benchmarking.md) doc is not up-to-date. For example, in section 1, `application_test.py` is no longer in our repo. It would be great if someone could take a look.

**Comment by ScottTodd** [comment]
Looks like the TensorFlow bits of that document have been stale for a while, particularly with https://github.com/google/iree/pull/8078.

These docs are more up to date:
* https://github.com/google/iree/blob/main/docs/developers/debugging/tf_integrations_test_repro.md
* https://github.com/google/iree/tree/main/benchmarks#iree-benchmarks

**Comment by ScottTodd** [comment]
I think I deleted the most out-of-date benchmarking doc. 

These pages are _somewhat_ up-to-date:
* https://iree.dev/developers/performance/benchmarking/
* https://iree.dev/developers/performance/benchmark-suites/
