### ISSUE TITLE
Add macOS buildbot

### ISSUE THREAD

**Issue by antiagainst** [openxla/iree#9486]
We have a mac mini sitting idly in the test lab. It would be nice to set it up so that we can build/test on macOS to guard against regressions. Right now we sort of rely on the release channels to make sure we can build IREE artifacts for macOS.

**Comment by GMNGeoffrey** [comment]
Agreed, and this is on the todo list (though I guess there wasn't an issue filed), but I don't think it should be assigned unless someone is planning to imminently work on it. Otherwise you end up with issues that no one touches because they think someone else is already working on it.

**Comment by powderluv** [comment]
FWIW while we wait for the official IREE bot we have a downstream SHARK macOS perf-bot https://github.com/nod-ai/SHARK/runs/6873821492?check_suite_focus=true#step:4:291  . Right now it is only CPU but once I verify Spirv for those models I will enable those too.

**Comment by ScottTodd** [comment]
Would GitHub's hosted runners work well enough for a macOS CI?
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by GMNGeoffrey** [comment]
Maybe for postsubmit only. We don't have the option for bigger managed runners on Macs, so we're stuck with the tiny default ones

**Comment by antiagainst** [comment]
Assigning to myself--I'm looking into this now.

**Comment by antiagainst** [comment]
This is done now with https://github.com/openxla/iree/pull/12501 that enables postsubmit checks.

**Comment by GMNGeoffrey** [comment]
We now have access to the big mac runners. https://github.com/openxla/iree/pull/12725 is my attempt to use them, but there's some issue installing ninja. I'd guess that the venv isn't getting preserved across steps...

**Comment by GMNGeoffrey** [comment]
Filed https://github.com/openxla/iree/issues/12727 to track
