### ISSUE TITLE
Run SHARK model suite on IREE post-submit 

### ISSUE THREAD

**Issue by julianwa** [openxla/iree#9537]
We'd like to include a run of the sizeable model suite that Nod.ai is developing in IREE post-submits:

https://github.com/nod-ai/SHARK
https://github.com/nod-ai/SHARK/runs/6920622600?check_suite_focus=true

Current execution time is 1h45m. Can be sharded as necessary.

@GMNGeoffrey wants to provide input on whether the workflow should always succeed, or fail on non-xfail tests failing.

@powderluv: Can you or your team create the workflow to run this? Note that our self-hosted runners are going to be delayed -- is it possible to stand up a version with just 1 model that can run in a reasonable amount of time on Github-hosted runners? When we get the self-hosted runners working, should this be run on an a2-highgpu-1g?

**Comment by julianwa** [comment]
@powderluv I'm copying questions from above in case you missed them:

Can you or your team create the workflow to run this? Note that our self-hosted runners are going to be delayed -- is it possible to stand up a version with just 1 model that can run in a reasonable amount of time on Github-hosted runners? When we get the self-hosted runners working, should this be run on an a2-highgpu-1g?

**Comment by powderluv** [comment]
I can make the SHARK runners use stock IREE nightly releases and run the same tests.

**Comment by julianwa** [comment]
how long do you estimate just the test execution (excluding the build) will take on a Github-hosted runner?

**Comment by powderluv** [comment]
GH runner fails some tests since it is a dual core VM with limited RAM. We can pick a few tests that pass there and avoid any benchmarking

**Comment by julianwa** [comment]
Sounds good. Would the IREE workflow checkout the shark repo to gain access to the test scripts, etc? Seems sub-optimal to duplicate those in the IREE repo.

**Comment by alliemartens** [comment]
Assigning to @GMNGeoffrey to help get the runner setup.

**Comment by powderluv** [comment]
Should be easy to add. I can take this. Is there an example of a workflow taking a post submit and building an IREE compiler / runtime wheel ? Once we have that it is easy for me to wire into the shark test suite.

**Comment by GMNGeoffrey** [comment]
https://github.com/iree-org/iree/blob/main/.github/workflows/build_package.yml

**Comment by julianwa** [comment]
One other note from Geoffrey: make sure that the workflow checks out a specific commit of the shark repo -- we'll update it manually as needed

**Comment by alliemartens** [comment]
From meeting today, draft PR up, @powderluv checking

**Comment by julianwa** [comment]
draft PR: #9748

**Comment by alliemartens** [comment]
PR should be in review today

**Comment by alliemartens** [comment]
PR still in draft today FYI

**Comment by alliemartens** [comment]
PR is still in draft as of today

**Comment by alliemartens** [comment]
PR is still in draft as of today

**Comment by erob710** [comment]
Merge PR with ability to disable.

**Comment by allieculp** [comment]
Is this closed?

**Comment by mariecwhite** [comment]
Yep
