### ISSUE TITLE
Split IREE_BUILD_BENCHMARKS into IREE_BUILD_BENCHMARKS_TF/TFLITE

### ISSUE THREAD

**Issue by pzread** [openxla/iree#9668]
### Request description

Since TF/TFLite benchmark suites require different importers to be installed, splitting the benchmark options allows users to only install the required importers for the benchmarks they want to run.

### What component(s) does this issue relate to?

Other

**Comment by alliemartens** [comment]
Hey @pzread, can you give this issue a priority?

**Comment by pzread** [comment]
This issue is no longer relevant in the new benchmark suite (and we switch to using imported mlir)
