### ISSUE TITLE
Drop `CPUAArchDoubleTilingExpert`

### ISSUE THREAD

**Issue by bjacob** [openxla/iree#9710]
This entire code path should be possible to remove, by making mmt4d go through the same expert as the rest.

**Comment by alliemartens** [comment]
@bjacob can you help assign a priority to this issue?

**Comment by bjacob** [comment]
done - but for this one i'm still working out on the exact contour of what we want to do here. might need to rephrase this one.

**Comment by allieculp** [comment]
@bjacob Stale P1 item here, is this still open?

**Comment by bjacob** [comment]
good catch!
